### ISSUE TITLE
Fix dead link in DatePicker documentation page

### ISSUE THREAD

**Issue by aflashyrhetoric** [carbon-design-system/carbon-website#1200]
## What package(s) are you using? 

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
In [this section](https://www.carbondesignsystem.com/components/date-picker/usage/#content) of the Carbon docs, there is a dead link in the text that reads:

> See the date picker code documentation for more info.

The href for this link 404's: https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/date-picker/README.md

## Relevant information

After checking the Storybook and other places for a general overview on the DatePicker component, I'm not sure how this should be updated. With some direction I'd be happy to create a PR.

**Comment by jeanservaas** [comment]
@aflashyrhetoric I cannot find the dead link anymore. We may have updated Date Picker usage docs since this issue was created. Also, there's a quick way to open a PR for things like this at the bottom of the page if you come across something like this in the future.

![image](https://user-images.githubusercontent.com/43144260/124653910-e0d73800-de6b-11eb-9b6a-41c06e71086d.png)

**Comment by aflashyrhetoric** [comment]
Awesome! Thanks so much for your awesome work in maintaining this - apologies, I'll try to submit a direct PR in the future!
