### ISSUE TITLE
Add new IBM Equal Access resource and tools cards to the Accessibility guidelines page 

### ISSUE THREAD

**Issue by snidersd** [carbon-design-system/carbon-website#1201]
##Carbon Design System -> Accessibility-> Resources
https://www.carbondesignsystem.com/guidelines/accessibility/overview#resources
1. Add a new card in front of the others (if possible):
![tool](https://user-images.githubusercontent.com/21676914/82081858-a4b3a780-96ac-11ea-88b5-ab1d47692c8f.png)
2. Remove Card to IBM Accessibility Quick Guidance IBM accessibility quick guidance - (Internal only)
3. Update the icon in the IBM Accessibility Checklist card to the new A11y bee logo.
[BE_for_Accessibility_darker.svg.zip](https://github.com/carbon-design-system/carbon-website/files/4636253/BE_for_Accessibility_darker.svg.zip)

##Carbon Design System -> Accessibility-> Tools
https://www.carbondesignsystem.com/guidelines/accessibility/overview#tools
1. Add a new card in front of the others (if possible):
![equal](https://user-images.githubusercontent.com/21676914/82082278-5652d880-96ad-11ea-98ff-69232ba94f4d.png)

[IBM Equal Access Toolkit](https://www.ibm.com/able/toolkit) with bee logo.
2. Recommend the icon used for Nocoffee vision simulator changes to something other than the IBM Bee.

**Comment by snidersd** [comment]
@dakahn Is it possible to get an estimate on when the updates will be completed? Also, let me know if any additional information is needed. Thx!

**Comment by dakahn** [comment]
Do we have any blockers to getting this done? We probably shouldn't link to obsolete tooling.

**Comment by jeanservaas** [comment]
Hey @dakahn I thought we were going to add the aperture icon here. Also, there wasn't a designer on this review.

**Comment by dakahn** [comment]
@jeanservaas you gave me three options -- adding _our_ icon to something we don't make didn't sense to me so I went with the 'leave it out' option. (granted after saying i'd do the opposite, my bad) 

Had multiple designers (content, visual) weigh in on the PR figured we were good to go. Still getting a hang of the website update workflow personally. If it's a problem problem we can roll it back. Otherwise I'll wait for explicit approval from a designer moving forward.

**Comment by dakahn** [comment]
I'm going to close this up as resolved for now, but can reopoen if i need to
