### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by tsaitsaitsai** [carbon-design-system/carbon-website#1234]
Link > Style > Typography: 
Link text should be ~set in~ set in sentence case with the first letter of each word capitalized. Links should not exceed three words.

**Comment by tsaitsaitsai** [comment]
:+1: Good to know. Just curious, what's the thought process behind not using sentence case v10 on?

**Comment by alisonjoseph** [comment]
@tsaitsaitsai We haven't changed anything around when to use sentence case, I think the wording was removed here because someone found it confusing in regard to links. Links will follow whatever capitalization rules depending on where they are. All the capitalization rules can be found here https://next.carbondesignsystem.com/guidelines/content/guidance#capitalization
