### ISSUE TITLE
Can we add a clickable tile version with a download icon instead of a linkout button?

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#1299]
### Summary

Currently, the clickable tile component only has `type="resource"` with a link-out icon in the bottom right.

As we are introducing actions like direct-downloads for Sketch libraries, it would be great to have a version of the resource tile with a download icon instead. This would allow us to simplify title language as it will be clear the tile triggers a download.

This shouldn't be a big project, and should probably just require a dev to pull in the icon and create a version.

### Specific timeline issues / requests

It would be awesome to have this before we launch v10, but not stop-ship, obviously.

**Comment by designertyler** [comment]
This tile should be the same as the resource tile with the only difference being that it uses the clouddownload icon instead of the launch icon.

<img width="144" alt="Screen Shot 2019-03-14 at 3 01 27 PM" src="https://user-images.githubusercontent.com/19270502/54387708-125be200-466a-11e9-8139-9336462f765d.png">

**Comment by connor-leech** [comment]
Also creating a tile resource for links to elsewhere on the Carbon site would be useful, re: #1580
