### ISSUE TITLE
Slider.js on mobile w/ vanilla javascript

### ISSUE THREAD

**Issue by tfrankie88** [carbon-design-system/carbon-website#1393]
## Summary
Slider functionality is immobile on mobile devices

## Relevant information
Using vanilla js for a php site. When browser/mobile testing carbon slider component functionality is broken. In vanilla slider.js I noticed there is no "touchmove" event listeners. Please see [example page](https://the-carbon-components.netlify.app/?nav=slider) for reference.

Best,
Tfrankie88

**Comment by aledavila** [comment]
Hi there! :wave: Thanks for reaching out about this issue with the Vanilla JS set of components. Unfortunately, the Vanilla JS components have been put in maintenance mode since our v10 release as our team has shifted focus to React. We try and help out as best we can but unfortunately no new development is occurring in that part of the codebase.

For teams looking to not use a framework for components, we recommend switching over to the Web Components library as that will be the strategy going forward in this area.

Hope this helps, let me know if you have any questions!
