### ISSUE TITLE
Content: Add characters remaining guidance to text input

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#1477]
## Overview

Under /components/form/usage we include a screenshot containing characters remaining on text input, but no guidance for using this feature. We had a user ask about guidance, and we should provide it.

### Screenshot on page:

<img width="748" alt="Screen Shot 2019-04-10 at 10 57 53 AM" src="https://user-images.githubusercontent.com/44656921/55894316-857c4980-5b7f-11e9-91c6-f42d0e45c90a.png">

### Slack request:

<img width="1367" alt="Screen Shot 2019-04-10 at 10 41 05 AM" src="https://user-images.githubusercontent.com/44656921/55894355-94fb9280-5b7f-11e9-9951-7b4c257a12a7.png">

**Comment by shixiedesign** [comment]
### 📖 Draft guidance content: 

Text fields and text areas may have a character limit and counter. Use the character limit and counter in order to communicate the requirements to users ahead of time, so they can format their input, and reduce negative experience of the error state when max character limit is reached.
