### ISSUE TITLE
implement solution for pages with a large number of tabs 

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon-website#1518]
**note:** it looks like we need to do some design & IA work around how & where we're exposing tabs. can discuss in this issue if desired

---

"tab stacking" specs & comments (tabs convert to dropdown) from this original thread: https://github.com/carbon-design-system/carbon-website/issues/578 (multiple PR's worth of issues in that thread, so breaking apart here for tracking)

@jeanservaas 's [comment in the above issue](https://github.com/carbon-design-system/carbon-website/issues/578#issuecomment-463360990) lists specs fo this, quoted here: 

After mike saw the stacking spec, he wanted a slight pivot in the design... he did not want us to go to 50% of the screen with two tabs at mobile anymore.

- [ ] Two banner tabs will not go 50/50 on the screen at mobile anymore but will stay as they are now on the carbon site

- [ ] Our tab component (the in-page component seen on the motion page) the uses a minimum width to make tabs all equal width if they are under a certain character count; it would be nice to do something like this with our banner tabs as well (or add some light JS)

- [ ] blue highlight is 3px tall (not 2px)

- [ ] at 3 or more banner tabs, they will revert to full screen dropdown in mobile

Here are the updated responsive design specs for the banner tabs:

### Two tabs

<br>

**2 tabs at Desktop**

![2_tabs_desktop](https://user-images.githubusercontent.com/43144260/52741617-64daad80-2f9b-11e9-8053-a44b13f04c7b.png)

**2 tabs at Tablet**
![2_tabs_672](https://user-images.githubusercontent.com/43144260/52741543-31981e80-2f9b-11e9-835f-884940e4287f.png)

**2 tabs at Mobile**
![2_tabs_mobile](https://user-images.githubusercontent.com/43144260/52741544-31981e80-2f9b-11e9-8a70-cfafc624b302.png)

<br>

### Three or more tabs

 **3 tabs at Desktop**
![3 _tabs_desktop](https://user-images.githubusercontent.com/43144260/52741789-d0247f80-2f9b-11e9-9259-1aa32aaae5ed.png)

 **3 tabs at Tablet**
![3_tabs_672](https://user-images.githubusercontent.com/43144260/52741684-92275b80-2f9b-11e9-9767-b4936dfd38f1.png)

**3+ tabs at Mobile**
![3_tabs_mobile](https://user-images.githubusercontent.com/43144260/52741685-92275b80-2f9b-11e9-99fc-7ac8c19a66b2.png)

### Color specs for dark theme dropdown (gulp)

![image](https://user-images.githubusercontent.com/43144260/52742427-5097b000-2f9d-11e9-8f96-c57e2f52777a.png)

(can also get you exact tokens if you need)

**Comment by mjabbink** [comment]
@jeanservaas Stacking tabs? We are not doing stacking or doing drop down tabs so am I confused here? Please clarify.

**Comment by mjabbink** [comment]
@jeanservaas I thought the plan was to reduce the width of tabs in mobile (they’re current mega wide with tones of extra space on the right side) so there could easily be 3 and maybe 4 tabs present or a horizontal scroll if necessary. We should not be creating situation where there might be more than 4 tabs anyways.

**Comment by lovemecomputer** [comment]
@mjabbink i agree that >4 tabs is not desirable, however we are also providing our code and design as a reusable library for anyone in IBM. we can encourage IA strategies, but we don't get to see every single app or webpage that folks make, so we need to have some kind of affordance for folks that would go against the max-4 tab guideline so the website looks alright even in that circumstance.

i think we can also see on the carbon website some edge cases that go over 4 tabs. we could reorganize but i think sometimes in a case like this, where we're providing technical documentation for multiple kinds of users, sometimes we're going to end up needing more than 4 tabs (or whatever manifestation it takes) any rigidly-established hierarchy on a website is going to have the occasional edge case like this

**Comment by jeanservaas** [comment]
@mjabbink we are working on this spec now.

Audrey has already fixed the tab width to match IDL in desktop, she will do the same in mobile too but we will still have some situations, even capping the tab # at 4 where a horizontal scroll will happen.

The reason the tabs revert to dropdown in that scenario is because that's how the Carbon component functions... we don't need to keep that functionality, but we do need to spec out a horizontal tab scroll behavior for Audrey, otherwise we end up with what we have now, which is the whole page having a gross horizontal scroll in mobile. 

@shixiedesign sent this over as an example:

https://github.com/carbon-design-system/carbon-website/files/3128486/file_from_ios.mp4.zip

(mp4 will download if you paste this into url, sorry this is grandma way... git won't let me embed mp4)

I know we want to encourage people to keep their tabs to a minimum, but we still need to solve/consider these UX issues:
- how to visually indicate the existence of more tabs outside screen, esp. if no tabs are cropped
- scroll a cropped tab to center / left / right align when user select it? If left align, it looses visual indicator that more tabs exist on the left
- infinite horizontal scroll or not

**Comment by mjabbink** [comment]
makes sense. Again, the websites are different than product so having both options is a plus. I think using tabs in mobile is certainly a smart move but in case of our eco system sites which are more controlled when it comes to content we can use a bespoke approach which is also a good approach as well.

**Comment by lovemecomputer** [comment]
marking as un-stale bc i think there is still some ongoing design/specification on this issue
