### ISSUE TITLE
[Content] Need content for contribution in iconography page

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#161]
Currently we provide a usage page for iconography here: http://staging.carbondesignsystem.com/guidelines/iconography/contribution

Ideally, we would have a matching one for experimental at `/experimental/iconography/contribution` when #96 is done. This page should have any updated content that we would want to switch over to in Carbon X.

**Comment by joshblack** [comment]
cc @chrisconnors-ibm

**Comment by chrisconnors-ibm** [comment]
Scope: if appropriate content exists @ ['duo' website](https://duo.w3ibm.mybluemix.net/elements/icons/contribute) migrate it over to augment/increment what's found at http://design-system.stage1.mybluemix.net/style/iconography/contribution

**Comment by alisonjoseph** [comment]
FYI http://staging.carbondesignsystem.com/experimental/iconography/contribution

**Comment by claycrenshaw** [comment]
Draft 1 ready for feedback: https://ibm.biz/BdYuYx

@chrisconnors-ibm @joshblack

**Comment by chrisconnors-ibm** [comment]
The icons in our packages are 16 x 16 or 32 x 32 - there's a reference to 24 px icons.

**Comment by claycrenshaw** [comment]
Round 2 ready for feedback: https://ibm.biz/BdYLze

@chrisconnors-ibm @joshblack @designertyler @aagonzales

**Comment by claycrenshaw** [comment]
@chrisconnors-ibm @aagonzales 

Are we going to drop references to 32 px icons (per conversation yesterday)? Thanks.

**Comment by chrisconnors-ibm** [comment]
If we do we need to articulate _why_ our icons are principally 16x16

**Comment by claycrenshaw** [comment]
@aagonzales Do you have any insight into the 16x16 rationale? Thanks!

**Comment by aagonzales** [comment]
Oh yeah looks like we forgot to update our icon guidelines with the v9 release. Pre-V9 we had both 24px (ui icons) and 16px (glyph) icons. We've never had 32px icons for UI. 32 has only ever been used for service icons or pictograms which are essentially a variation of service icons.

When we updated to V9 we got rid of all our 24px icons and only were using 16px (because that was actually all that was being used in product, anything else is just too big and doesn't fit). 

16 works best with aligning to type. They complement each other in size. 16 also preserves space for information density.

**Comment by claycrenshaw** [comment]
Following up on this one. Latest content is pasted below. @jeanservaas @aagonzales Is this info (still) accurate? Thanks!

---
label: Experimental
title: Iconography
tabs: ['Library', 'Usage', 'Design and Contribution']
internal: true
---

1.  [Design and Production Guidelines](#design-and-production-guidelines)
- [Best Practices and Pro Tips](#best-practices-and-pro-tips)
- [Exporting SVGs](#exporting-svgs)
- [Contribution Process](#contribution-process)


## Design and Production Guidelines

Don't see the icon you need in the library? Make your own! Follow these guidelines to ensure visual consistency and proper formatting.

* All icons should be unique and not redundant with any existing icons in the system. Search the [library](/library) for the keyword(s) associated with your proposed new icon to ensure that it is not already represented.

* All icons should adhere to the [IBM Design Language visual style](https://w3.ibm.com/design/language/elements/icons/).

* All icons should comply with IBM [accessibility standards](/guidelines/accessibility/overview).

* All icons should be usable across all supported platforms and devices.

* All icons should be understandable by a global audience of users, regardless of nationality or language.

### Production-Ready 

To be considered production-ready, all icon submissions must be delivered in SVG format at 16 x 16 pixels. 

## Best Practices and Pro Tips

- Create a 16 x 16 px artboard for each icon.
- Icons should be at whole pixels. No decimals are allowed in x and y coordinates or width and height fields.
- Set your workspace up from the start to snap to pixels and round values to whole pixels to avoid correcting shapes later.
- Never use center borders. Centering can cause half pixels.
- Avoid using the line tool and use the rectangle tool instead. The line tool will place the vector on half pixels.
- Be aware of automatic alignments which can place vectors on uneven or half pixels.
- Each artboard and the artwork within it must be aligned to the pixel grid.
- All strokes must be expanded.
- All strokes must be full pixels.
- Do not include padding when exporting icons (internal and external padding can be added with CSS).
- Combine all possible shapes and paths.
- Ungroup icon layers completely. The icon should be on the top-most layer in your artboard.
- Make sure to properly name layers and artboards (these names will also be exported into the code).

## Exporting SVGs

### Export SVGs from Sketch

1. Draw a 16 x 16 px artboard. The artboard should hug the edges of the icon.
2. Place the icon squarely on the artboard, making sure it's aligned to the pixel grid.
3. Convert all strokes to outlines `(Shift + ⌘ + O)`
4. Select any overlapping shapes and click the Union icon from the top navigation to merge all of the shapes together.
5. Make sure the icon is at `#000000` and has no additional styling.
6. Select the entire artboard (not just the icon).
7. Click `Make Exportable` at the bottom of the right toolbar in Sketch.
8. In the `Export` widget select "SVG" in the format dropdown.
9. Click `Export 'Artboard-Name'`.
10. Name icon with the `#name--modifier` convention. (ex. copy.svg, copy--glyph.svg, add.svg, add--glyph.svg).



### Export SVGs from Adobe Illustrator

1. Draw a 16 x 16 px artboard. The artboard should hug the edges of the icon.
2. Place the icon squarely on the artboard, making sure it's aligned to the pixel grid.
3. Expand all strokes `(Object > Expand)`.
4. Select all overlapping shapes and click the "Unite" icon in the Pathfinder panel to merge all of the shapes together.
5. Make sure the icon is at `#000000` and has no additional styling.
6. Select `File` > `Save a Copy...`` from the top navigation.
7. On the `Format` dropdown select "SVG."
8. Below `Format` select `Use Artboard`, then select either all or a range of artboards, depending on your need.
9. Click `Save`.
10. The `SVG Options` dialog will then open.
11. Make sure the preferences are the same as in the image below.

![export an icon from illustrator](images/icon-contribution-3.png)

## Contribution Process

Does your icon have potential for other products at IBM? If so, please consider contributing to the design system. IBM welcomes icon contributions in the form of a pull request to our [icons repository](https://github.com/IBM/carbon-icons). If you're unable to make a pull request, please [submit an issue in the repo](https://github.com/IBM/carbon-icons/issues/new) with the icon attached.

Please note that Carbon contribution is **not required** in order to introduce a new icon into your product's UI. If your icon is determined to be broadly useful in Carbon and passes IBM Brand design reviews, then it may also be integrated into the design system.

If your icon submission is accepted, we will notify you. If changes are needed, you'll need to create a new contribution issue after reworking it based on feedback from the Design System and Brand teams.

**Comment by aagonzales** [comment]
### Feedback
Looks pretty good to me. Just a couple of things we need to confirm or re-order:
- We need to confirm with @joshblack what the icon name convention is.
- I think we're gonna have people submit a 32x32 px AND a 16 x16 px versions - correct? @chrisconnors-ibm  
- As an aside we'll need to add the sizing and how to scale/use the 32px icons to the usage page.
- I think we should actually divide out the best practices and pro tips. It was a little hard to process with so many points together. Best practices is more about making the actual icon and pro-tips is more like process and tooling advice. Below is how I would group them. I'd might even recommend we move them under "production ready" because those are qualities we look for to approve something as "production ready". 

__________________________

**Production Best Practices**
- Create a 16 x 16 px **or 32 x 32 px** artboard for each icon.
- Each artboard and the artwork within it must be aligned to the pixel grid.
- Icons should be at whole pixels. No decimals are allowed in x and y coordinates or width and height fields.
- All strokes must be expanded.
- All strokes must be full pixels.
- ~Do not include padding when exporting icons (internal and external padding can be added with CSS).~ *Not true anymore with Duo styles*
- Combine all possible shapes and paths.
- Ungroup icon layers completely. The icon should be on the top-most layer in your artboard.
- Make sure to properly name layers and artboards (these names will also be exported into the code).

**Pro-tips:**
- Set your workspace up from the start to snap to pixels and round values to whole pixels to avoid correcting shapes later.
- Never use center borders. Centering can cause half pixels.
- Avoid using the line tool and use the rectangle tool instead. The line tool will place the vector on half pixels.
- Be aware of automatic alignments which can place vectors on uneven or half pixels.

**Comment by chrisconnors-ibm** [comment]
I assume teams making icon assets for use in components _need_ 16 x 16; if they are making service icons or similar they need 32 x 32 and probably _not_ 16 x 16. 

Our set of 16 x 16 is a specific subset of the 32 x 32 library; but there's no real harm in advocating that  teams create both.

**Comment by claycrenshaw** [comment]
@joshblack Can you confirm the naming convention here? Thanks!

**Comment by claycrenshaw** [comment]
@aagonzales and @chrisconnors-ibm 

So to make sure I'm clear on the new direction:

We are back to asking for both a 32px and 16px version of every icon submitted, right? 
(This is what we had before and I was asked to change it to just 16. . .)

Are there any use cases where a team would only need the 16px icon?

How do I (as a product team designer) know when to use the 32px icon? Is it only for the cloud catalog?

Thanks!

**Comment by chrisconnors-ibm** [comment]
> Are there any use cases where a team would only need the 16px icon?

they are making icon assets for use in a component _only_ and never used or displayed at sizes greater than 16 x 16

>How do I (as a product team designer) know when to use the 32px icon?

You need an icon rendered at any size above 16 x 16, such as in service catalog

When would you make both?
If they need it rendered at 16x16 (as in a component) _and_ at larger sizes. not sure what the actual use case for that is.

The giant pre-condition for all of this being "Our team is creating a new component requiring icon assets that doesn't exist and plan to submit it for inclusion in the main IBM Design System Branch".

I don't think anyone is going to just expand the library for the sake of just having more icons.

**Comment by claycrenshaw** [comment]
Revised content below.

**Comment by claycrenshaw** [comment]
---
label: Guidelines
title: Iconography
tabs: ['Library', 'Usage', 'Design and Contribution']
---

1.  [Design and Production Guidelines](#design-and-production-guidelines)
- [Producing an Icon](#producing-an-icon)
- [Exporting SVGs](#exporting-svgs)
- [Contribution Process](#contribution-process)


## Design and Production Guidelines

Don't see the icon you need in the library? Make your own! Follow these guidelines to ensure visual consistency and proper formatting.

* All icons should be unique and not redundant with any existing icons in the system. Search the [library](/library) for the keyword(s) associated with your proposed new icon to ensure that it is not already represented.

* All icons should adhere to the [IBM Design Language visual style](https://w3.ibm.com/design/language/elements/icons/).

* All icons should comply with IBM [accessibility standards](/guidelines/accessibility/overview).

* All icons should be usable across all supported platforms and devices.

* All icons should be understandable by a global audience of users, regardless of nationality or language.

## Producing an Icon

- Create a 16 x 16 or 32 x 32 px artboard for each icon.
- Set your workspace up from the start to snap to pixels and round values to whole pixels to avoid correcting shapes later.
- Never use center borders. Centering can cause half pixels.
- Avoid using the line tool; use the rectangle tool instead. The line tool will place the vector on half pixels.
- Be aware of automatic alignments which can place vectors on uneven or half pixels.
- Do not include padding when exporting icons (internal and external padding can be added with CSS).
- Ungroup icon layers completely. The icon should be on the top-most layer in your artboard.
- Make sure to properly name layers and artboards (these names will also be exported into the code).

### Production-Ready 

To be considered production-ready, all icon submissions must be delivered in SVG format at 16 x 16 pixels (for integration with Carbon components) or 32 x 32 (for service icons). 

- Icons should be at whole pixels. No decimals are allowed in x and y coordinates or width and height fields.
- Each artboard and the artwork within it must be aligned to the pixel grid.
- All strokes must be expanded and at full pixel values.
- All possible shapes and paths should be combined.

## Exporting SVGs

### Export SVGs from Sketch

1. Draw a 16 x 16 or 32 x 32 px artboard. The artboard should hug the edges of the icon.
2. Place the icon squarely on the artboard, making sure it's aligned to the pixel grid.
3. Convert all strokes to outlines `(Shift + ⌘ + O)`
4. Select any overlapping shapes and click the Union icon from the top navigation to merge all of the shapes together.
5. Make sure the icon is at `#000000` and has no additional styling.
6. Select the entire artboard (not just the icon).
7. Click `Make Exportable` at the bottom of the right toolbar in Sketch.
8. In the `Export` widget select "SVG" in the format dropdown.
9. Click `Export 'Artboard-Name'`.
10. Name icon with the `#name--modifier` convention. (ex. copy.svg, copy--glyph.svg, add.svg, add--glyph.svg).



### Export SVGs from Adobe Illustrator

1. Draw a 16 x 16 or 32 x 32 px artboard. The artboard should hug the edges of the icon.
2. Place the icon squarely on the artboard, making sure it's aligned to the pixel grid.
3. Expand all strokes `(Object > Expand)`.
4. Select all overlapping shapes and click the "Unite" icon in the Pathfinder panel to merge all of the shapes together.
5. Make sure the icon is at `#000000` and has no additional styling.
6. Select `File` > `Save a Copy...`` from the top navigation.
7. On the `Format` dropdown select "SVG."
8. Below `Format` select `Use Artboard`, then select either all or a range of artboards, depending on your need.
9. Click `Save`.
10. The `SVG Options` dialog will then open.
11. Make sure the preferences are the same as in the image below.

![export an icon from illustrator](images/icon-contribution-3.png)

## Contribution Process

Does your icon have potential for other products at IBM? If so, please consider contributing to the design system. IBM welcomes icon contributions in the form of a pull request to our [icons repository](https://github.com/IBM/carbon-icons). If you're unable to make a pull request, please [submit an issue in the repo](https://github.com/IBM/carbon-icons/issues/new) with the icon attached.

Please note that Carbon contribution is **not required** in order to introduce a new icon into your product's UI. If your icon is determined to be broadly useful in Carbon and passes IBM Brand design reviews, then it may also be integrated into the design system.

If your icon submission is accepted, we will notify you. If changes are needed, you'll need to create a new contribution issue after reworking it based on feedback from the Design System and Brand teams.

**Comment by claycrenshaw** [comment]
@alisonjoseph Please note the page title change from "contribution" to "design and contribution" here. Please hit me up with any questions!

**Comment by alisonjoseph** [comment]
Can you confirm this content is gettinng added here https://www.carbondesignsystem.com/guidelines/iconography/contribution and that this page is going away https://w3.ibm.com/design/product/experimental/iconography/library inn v10?

**Comment by joshblack** [comment]
Sorry for the delay here on naming conventions, I have this document right now:

https://github.com/IBM/carbon-elements/blob/master/docs/icons.md#prefixes

You can see the naming conventions in this demo: https://ibm.github.io/carbon-elements/icons/examples/esm/ and the code name for each by clicking on "expanded" at the top and viewing module name.

The gist of this is that the icon names should stay consistent with the naming found in the SVG source directory here: https://github.com/IBM/carbon-elements/tree/master/packages/icons/src/svg

When used in code, they become `PascalCase` so that `chevron--down` would become `ChevronDown`. In addition, size information is encoded to the end of the name so that `16/chevron--down` would be `ChevronDown16`. If there is no size info (it's a top-level svg) then it's considered a glyph so `chevron--down` would be `ChevronDownGlyph` in code.

**Comment by shixiedesign** [comment]
Hi Clay, for **Export SVGs from Sketch (and Illustrator)**
> Draw a 16 x 16 or 32 x 32 px artboard. The artboard should hug the edges of the icon.
Above is no longer true. From what I know, Duo Icons come with a 2px padding, and are always drawn on 32x32 boards. Please verify @jeanservaas @aagonzales. thanks!

**Comment by shixiedesign** [comment]
Just confirmed we do have padding in icons and contribution guideline should update. Icons are drawn at 2 sizes, 16x16px and 32x32px. 16x16px sports 1 px padding all around, and 32x32px a 2px padding all around. Intruding the paddings are allowed on very selective moments to achieve visual balance.

**Comment by mjabbink** [comment]
@claycrenshaw   "Design and production guidelines"  can just be "Guidelines" 

When I read the copy it’s just guidance. It’s not Design and Production guidance. I also still see the tab is named "Design and Contribution" and it should just be "Contribution" as per my earlier issue a few weeks back. This page content is not design guidance but rather contribution guidance. "Usage" tab covers design. It will also help make the title more simple and actually more straight forward and less wordy when they don’t need to be.
