### ISSUE TITLE
Add .ase and .clr files resource tile to "Resources" and "Getting Started: Designers"

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#1644]
Make sure https://www.carbondesignsystem.com/resources has all the resources we offer; if it's required to set up the design environment, it should also be on https://www.carbondesignsystem.com/getting-started/designers

![image](https://user-images.githubusercontent.com/35537391/57973989-0e588300-797f-11e9-820b-a7efe20d3cc7.png)

**Comment by connor-leech** [comment]
I don't believe the color palettes are _required_ for setting up the design environment. @aagonzales or @laurenmrice, can you confirm?

I'll add to the resources page.

**Comment by aagonzales** [comment]
Yeah I wouldn't say its "required" for the kit because the palettes are already in the IDL kit and in the theme palettes are in the theme kits. But it can be used with Sketch and other programs (Illustrator, Keynote, etc). 

So having it on the resource page and on the color page makes sense. Its also not clear on how to actually add a .clr file to your system so if we add it to getting started page we might want to add guidelines on what you should do after you hit the download. (I'm actually not super clear on that part either)

**Comment by chrisconnors-ibm** [comment]
if you put the .clr file in `~/Library/Colors` it appears in the Color Picker window wherever it's supported.

**Comment by chrisconnors-ibm** [comment]
Open the Color Picker window (From Sketch or Preview etc.) click the swatches tab. Next to the current swatch there's a gear, click it:
![image](https://user-images.githubusercontent.com/35537391/58343516-35043700-7e21-11e9-900d-ceac851d8fca.png)

Use the `Open` command and select our swatch.

**Comment by chrisconnors-ibm** [comment]
you can also copy the .clr file directly to `~/Library/Colors` with Finder or the command line; it then appears in the Color Picker window wherever it's supported.

**Comment by chrisconnors-ibm** [comment]
if it's not a required step this is done when it gets to Resources.
