### ISSUE TITLE
Merge "Product" and "Digital" into "Carbon" menu link in the top right switcher menu

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#1645]
Remove the link to "Digital".
Change "Product" to "Carbon".
Add a link to the Digital PAL to his page - https://www.carbondesignsystem.com/community/domain-guidance.

![snippet](https://user-images.githubusercontent.com/825457/91766013-7e544200-eb9f-11ea-8237-7455890f26bb.png)

**Comment by mjabbink** [comment]
@shinytoyrobots Let’s talk more about this issue with this. The switcher is currently meant to represent the IBM Design Org. 
At the top we have IBM Design / Brand Center / IDL / Accessibility which represent the POV and Brand expression regarding design. Under those are the **Disciplines** and **Practices**. It currently takes you to the site that represents that design discipline. The flaw in this structure is that Product and Digital are really just one Design system (including PALs via Carbon site) which should really be a merged discipline since both dependent on the same design system (Carbon).

It’s not just a place where links to useful things exist. I also suggest running whatever solution by Todd since he’s close to this and drove this current list of items. It’s definitely not right as is but the solution will include other updates/considerations within the sites. i.e adding an About on IDL left nav, adding a large card at the top of IDL to aim to Carbon, updating the switcher, finessing language and clarity in Carbon site, etc. All of these need to be addressed together.

**Comment by laurenmrice** [comment]
The app switcher panel content has changed since this issue was originally opened. Is the current content structure in a good place?
<img width="286" alt="Screen Shot 2022-10-25 at 11 45 34 AM" src="https://user-images.githubusercontent.com/43969356/197820452-434596fc-f5a6-4bb6-937f-e2c428e5313e.png">
