### ISSUE TITLE
Bahaviour on mobile screen

### ISSUE THREAD

**Issue by kingsleytth** [carbon-design-system/carbon-website#1648]
Hi Carbon Design Sytem,

First of all, I would like to thank you for creating this design system. It is super helpful and I can have more confidence to use this system to design my system. Love it.

I have one feedback or maybe consider a request. Is it possible to have more info or example for the mobile behaviours? For example, I noticed the tabs will change it to a dropdown on a mobile screen. Is there any reason behind it? Why dropdown and why not using scrollable on mobile? Can we have more behaviour explanation on a mobile screen?

Thank you.

Best Regards,
Kingsley

**Comment by laurenmrice** [comment]
Hi @kingsleytth 👋

We recently have changed out Tab component mobile behavior to have a horizontal scroll instead of changing it to a dropdown. https://carbondesignsystem.com/components/tabs/usage/#live-demo

There are plans to have more mobile guidance for components but for now it is in our backlog. Feel free to reopen if you have any other questions.
