### ISSUE TITLE
Data table: live demo controls not working

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#1687]
- [ ] The zebra stripes control not working in non-white themes.
- [x] FIXED The row size controls are not working in the live demo.
https://www.carbondesignsystem.com/components/data-table/usage#live-demo

![image](https://user-images.githubusercontent.com/11670886/92750886-7d68a080-f355-11ea-9855-c6d59d6f5859.png)

**Comment by tw15egan** [comment]
Seems like this is due to `...getTableProps()` on `Table` being called _after_ the prop is added to the component. I'm not too sure how all the demos are rendered though 😬

![Screen Shot 2020-09-10 at 12 29 12 PM](https://user-images.githubusercontent.com/11928039/92791133-45675a80-f361-11ea-89a4-9d197d14c703.png)
