### ISSUE TITLE
Contribution: Toolbar low and high contrast

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon-website#1690]
@m-battelli commented on [Fri Jan 03 2020](https://github.com/carbon-design-system/carbon/issues/4948)

**Brief description**

I have designed a new pattern using standard components of the Carbon Design System (V10).
It is an useful pattern, easily standardable to be included in the Carbon library and easily customizable based on the use cases.
Essentially, the toolbar could be part of the widest range of products where it is necessary a main actions set ready to use and positionable in the most suitable way on the screen.
I have explored visually the low and high contrast versions for consistency with the rest of standard components. 

**White theme**
![Toolbar White](https://user-images.githubusercontent.com/47557215/71736129-8ca36000-2e50-11ea-9c90-bead02dc7831.png)

**Gray 10 theme**
![Toolbar Gray 10](https://user-images.githubusercontent.com/47557215/71736151-a0e75d00-2e50-11ea-80dc-91b9da6091b2.png)

**Gray 90 theme**
![Toolbar Gray 90](https://user-images.githubusercontent.com/47557215/71736192-bb213b00-2e50-11ea-9ca7-d5f6a4081ceb.png)

**Gray 100 theme**
![Toolbar Gray 100](https://user-images.githubusercontent.com/47557215/71736221-cffdce80-2e50-11ea-9b62-db44dd0b6af1.png)

**Use case**
I have adopted this pattern to build and interact with diagram model.
This use case is available within Cloud Pak for Automation / Decisions.
<img width="816" alt="Screenshot 2020-01-03 at 17 10 27" src="https://user-images.githubusercontent.com/47557215/71736485-721db680-2e51-11ea-945e-1648dd5dda35.png">

<img width="815" alt="Screenshot 2020-01-03 at 17 10 44" src="https://user-images.githubusercontent.com/47557215/71736500-82359600-2e51-11ea-9810-c9022e591e0a.png">

---

@aagonzales commented on [Thu Jan 09 2020](https://github.com/carbon-design-system/carbon/issues/4948#issuecomment-572717054)

This is awesome! I only have one piece of feedback:

The dividers between sections should be a color instead of a cap, like the original toolbar. \
![image](https://user-images.githubusercontent.com/11670886/72098223-a5de5d80-32e3-11ea-980e-2d564fb31717.png)

**Comment by m-battelli** [comment]
Working on advanced toolbar with major number of actions.

**Comment by mjabbink** [comment]
@m-battelli the low contrast versions may have some color contrast ratio issues to solve to pass accessibility. The container itself probably fails on G10 and G90 theme above. Double check that the icons on the backgrounds have the right contrast to pass (in low contrast versions)

**Comment by aagonzales** [comment]
The low contrast is the as-is experience I believe for the existing toolbars. According to my understanding of non-text contrast rules the background only needs to be 3:1 contrast is there's no other indicator to determine where the interactive element is. 

@mjabbink I'm bet you're thinking of the content switcher issue. To my understanding that didn't pass because without the background in non-selected items the label just looks like body text in the content switcher. However here in a the toolbar I think the icons stand on their own as established actions and don't need to a 3:1 contrast background. This would be same for elsewhere in the system that we use icons for a trigger, like overflow menu or tooltip. 

That said I do think some of those colored icons on the G90 do look like they might fail contrast.

**Comment by mjabbink** [comment]
Yes. I guess if the container of the toolbar is not required to have the contrast then just the colored icons might have issues
