### ISSUE TITLE
[Type tokens] Inconsistent naming on website

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#1864]
Need to fix naming convention of type tokens on the website and a couple missing ones (Typography tabs)

---------------------------------------------------------------------------------------------------

**Expressive**
Headings
lg: `expressive-heading-05` might be calling what `expressive-heading-06` is? 
I think the heading-05 should be:
Size: 32px/2rem 
Line-height:40px / 2.5 rem
Weight: 400 / Regular
Letter-spacing: 0px

need to include:
`expressive-heading-06`
~~`expressive-heading-07`~~

Paragraphs and quotes and Display
- these do not have the word `expressive` in the token name in the most up to date elements package, except for `expressive-paragraph-01`. If we want to change these to have the word expressive in front of them, we will need to change that in code.

should be:
`quotation-01`
`quotation-02`
`display-01`
`display-02`
`display-03`
`display-04`

**Comment by asudoh** [comment]
Thanks @laurenmrice and @tw15egan! Moved to the website repo. @tw15egan Please let us know if you think this is a dup of #1852.

**Comment by laurenmrice** [comment]
Well the thing I am confused about is that the actual names of the tokens on the elements site, for the quotes and displays don't have `expressive` in front of them. https://carbon-elements.netlify.com/type/examples/preview/

**Comment by tw15egan** [comment]
What would the values be for `expressive-heading-05` through `expressive-heading-07`? Each one of these has defined steps, so we'd need to add in the values for each step [like so](https://github.com/tw15egan/carbon-website-gatsby/blob/ea5eb3d58f1cb1144bce82d039a1ced2ea830eb5/packages/addons-website/src/components/TypesetStyle/TypesetStyle.js#L238)

In regards to the second point, I added in the `expressive` to take care of the last point in this issue: https://github.com/carbon-design-system/carbon-website/issues/1583. If these tokens do not exist, should we revert those changes, or update the type tokens?

**Comment by tw15egan** [comment]
After taking a look at the type repo, it seems like they have always been just `quotation-01` etc... 

https://github.com/carbon-design-system/carbon/blob/master/packages/type/src/styles.js#L246

**Comment by tw15egan** [comment]
I also don't see `expressive-heading-07` in the netlify example 🤔

**Comment by jeanservaas** [comment]
Hey @laurenmrice 

1)
good call on the names -- I missed that and you're right, only headings have "expressive" in them.

should be:
quotation-01
quotation-02
display-01
display-02
display-03
display-04

2)
But in the .json file, we actually don't have and $expressive-heading-06 & 07

Those were only added to product because they're fixed. $Expressive-heading-05 actually grows through those sizes at breakpoints and then the Displays take over.

If we want to add those sizes for expressive headings... we're going to start running into the Display values.


Also, hmmm for some reason that orphaned "Heading" is still sitting there

![image](https://user-images.githubusercontent.com/43144260/62634693-ee8c8780-b8fb-11e9-9e67-26d47c72d21b.png)

**Comment by tw15egan** [comment]
That fix still hasn't been merged (https://github.com/carbon-design-system/carbon-website/pull/1860), but I'll make another PR for the other updates
