### ISSUE TITLE
Create v11 branch

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2252]
See [comment below.](https://github.com/carbon-design-system/carbon-website/issues/2252#issuecomment-830098907)

~~Instead of creating a v11 staging branch, we are just going to create a website version for v10 and keep pushing v11 updates to the main branch~~

~~Need to do a branch/deploy for the `v10.carbondesignsystem.com` website.~~

Based off of this [slack conversation](https://ibm-studios.slack.com/archives/GD8JG6JR3/p1619537515001000?thread_ts=1619535913.000300&cid=GD8JG6JR3).

**Comment by alisonjoseph** [comment]
Thinking about this some more, it might be more confusing to have to send people back to `v10. `for current docs. 

I'd propose we do the same thing we did for the v10 release, since we aren't completely rebuilding the website this time it should be **much** easier to sync the two branches. 

- Create new `v11` or `next` branch that auto deploys to  `v11.carbondesignsytem.com` OR `next.carbondesignsystem.com`? I'd lean towards naming it v11, to not confuse things with Carbon Next. 😅 
- Keep pushing any content or regular website fixes etc to `main/www`
- Pull new `v11` content and releases into `v11` branch, and keep synced with `main` branch fixes. 

Thoughts @aagonzales @joshblack

**Comment by aagonzales** [comment]
Works for me, if it works for dev.
