### ISSUE TITLE
[Website Component] Component Example

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#230]
### Todo:
- [ ] responsive styles
- [ ] color/style updates
- [ ] spacing updates code snippet for code examples

<hr>
Designs for a improved component example.

Gather requirements first. Review the research digital has done.

Current asks:
Link out to codepen and story book.
move component switches to the right.
Can we bring in more "knobs" to the carbon site?

It's not clear that the links in the component example launch out to another tab. Add a link out icon or another indicator so it's clear React and Codepen are linkout out to a new tab and not controls to change the view.

![Screen Shot 2018-10-05 at 1.51.50 PM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/cd33d561-b4f6-492b-8528-de29553984e0)

![Screen Shot 2018-11-05 at 9.01.42 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/ad79fb6a-9724-4f9c-bfd2-e8d334c85f1c)

**Comment by shixiedesign** [comment]
Decided not to re-create new design for V10 release. Will make the following changes to current component: 
- for experimental, use white background
- for stable, adding 1px border

**Comment by jeanservaas** [comment]
# Component Window designs / page designs

https://ibm.box.com/s/2uhvlw7jpp69xck242lqf290a8306epj

- one weird thing is that we have a gray 10 background, and gray 10 is a prominent filed color, so we've had to add strokes around the gray 10 component window

- need to sketch stable component window... we want to show those on a white page background because of the light blue field 

- we'd like to explore a drop down for component variations, but realize this may need user testing

- need to link this issue back to the website page epic... (still working on the style tab)


![existing_functionality_02](https://user-images.githubusercontent.com/43144260/49254619-43801180-f3ef-11e8-8383-5bd6aa74fe50.png)

![new_functionality_01](https://user-images.githubusercontent.com/43144260/49254636-4e3aa680-f3ef-11e8-8b8b-360231daa62f.png)


![existing_functionality_02 copy](https://user-images.githubusercontent.com/43144260/49254627-47ac2f00-f3ef-11e8-8a70-69ca78ea2a35.png)

**Comment by aagonzales** [comment]
**Sprint 25:** double check whats being launched with v10.

**Comment by shixiedesign** [comment]
### Beta release requirement
Final style update based on below design. @jeanservaas could you upload final design and spec? Thanks! 
![img_0956](https://user-images.githubusercontent.com/15144993/49703976-31ae2380-fbd2-11e8-8636-852539171e37.jpg)

**Comment by jeanservaas** [comment]
## Website Component Example and Component Page Template

Sketch file: https://ibm.box.com/s/qiiiitr89578ismx279nmq8twbudjzpw

- This file has both an example template for Overview, Usage and Style tabs of the component page (for the Dropdown component for reference

- This file also has the breakpoint specs for the Component display window (functionality has not changed from current state Carbon, only styling... however, the mobile experience on the current carbon site for the component display window is broken

- Ideally, we are pulling from the new Carbon code snippet component but with dark theme values; however, this component also has to be revisited at the mobile breakpoint; it will require a new issue.

## Page Template Designs

![experimental_component_template_overview](https://user-images.githubusercontent.com/43144260/49820022-6dfd9300-fd3c-11e8-9c7a-df6ce1b5a780.png)

![experimental_component_template_usage](https://user-images.githubusercontent.com/43144260/49820028-71911a00-fd3c-11e8-9cbf-7f1e20f533f0.png)

![experimental_component_style](https://user-images.githubusercontent.com/43144260/49820033-75bd3780-fd3c-11e8-90f4-a08475904de3.png)

## Component Display Window Specs 

![1584](https://user-images.githubusercontent.com/43144260/49820110-a56c3f80-fd3c-11e8-87a4-5573b3fc1148.png)

![1056 lg 16 columns](https://user-images.githubusercontent.com/43144260/49820117-aac98a00-fd3c-11e8-8b0f-733c63a89e2f.png)

![672 md 8 columns](https://user-images.githubusercontent.com/43144260/49820124-aef5a780-fd3c-11e8-95e2-7e548d5ab048.png)

![320 sm 4 columns](https://user-images.githubusercontent.com/43144260/49820143-b61cb580-fd3c-11e8-852f-05b1d0a2644c.png)

**Comment by aagonzales** [comment]
Need a dev issue

**Comment by alisonjoseph** [comment]
This is mostly done, responsive styles still need to be added along w/ fixing the code snippet on the page.

**Comment by alisonjoseph** [comment]
duplicate. details in other issues
