### ISSUE TITLE
[Data vis: charts] Design

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#241]
# Designs for Charts pages: 

### Tab: Basic charts

![Dataviz-charts](https://user-images.githubusercontent.com/15144993/65063507-0405c000-d944-11e9-9897-6108f00a5dc6.png)

### Tab: Advanced charts

![Dataviz-charts-advanced](https://user-images.githubusercontent.com/15144993/65063542-1849bd00-d944-11e9-98a4-fc4f3b679c20.png)

**Comment by alisonjoseph** [comment]
@shixiedesign did you want us to match the chart example data to the sketch file?

stacked bar sketch file vs. code example
![Screen Shot 2019-09-18 at 8 33 04 AM](https://user-images.githubusercontent.com/2753488/65153210-fa856200-d9ee-11e9-8aa8-cea3027dc118.png)
![Screen Shot 2019-09-18 at 8 32 01 AM](https://user-images.githubusercontent.com/2753488/65153211-fa856200-d9ee-11e9-9c3d-913fe22e4886.png)

Also, I'm going to wait on adding the code snippets below, since that component isn't built and I assume we want it to match however we will be doing the updated React examples for components with theme switcher etc? (the one for components is custom and not really reusable right now) I'll come back to that part after helping finish up the Grid pages with Jeanne.
