### ISSUE TITLE
[pattern] status indicator grid issues

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#2435]
### Grid issues:
Also, the the status icon and status shape tables are not on grid, to the spec that was given. And they're not consistently off grid either. 

**See misalignment:**

![image](https://user-images.githubusercontent.com/43144260/123987918-95b5b480-d995-11eb-96cf-4b4e624686d6.png)

**Table specs:** (See complete table specs at breakpoints here)
https://github.com/carbon-design-system/carbon-website/issues/2199

To do:

- @vpicone we need to align the tables to the specs that were in the other issue; I didn't catch these discrepancies in my review

**Comment by mjabbink** [comment]
Let’s not forget about this grid, alignment fix. This should be addressed in the next sprint.

**Comment by mjabbink** [comment]
@alisonjoseph @joshblack Please make sure this is added to this sprint. This one can't slip through the cracks.

**Comment by alisonjoseph** [comment]
@mjabbink @jeanservaas I'll get @vpicone to chime in here also, but from my understanding this is using the Structured List component from Carbon which is _not_ grid-aware. It would likely require a complete re-write of that component or a new one to be able to figure out a way to get this on-grid. That being said, I see the issue especially where the different tables don't align to each other, and wonder if there's something we could do to make it a little better until we have time to prioritize a new component?

**Comment by mjabbink** [comment]
@alisonjoseph @vpicone If the first two columns of icons are the same shouldn't those at least be the same in each structuralist? maybe as a first fix, those icons columns could be the same which would make a difference.

another issue
@alisonjoseph @jeanservaas @vpicone — I discovered in mobile the dark theme column is not visible or turned off. Should that be a separate issue or keep it here?

<img width="392" alt="Screen Shot 2021-08-04 at 11 21 52 AM" src="https://user-images.githubusercontent.com/32881239/128217790-057ef037-63ff-405d-a03d-ad54ee7fdae7.png">

**Comment by mjabbink** [comment]
@alisonjoseph @joshblack @aagonzales Please include this in the next sprint.

**Comment by mjabbink** [comment]
@alisonjoseph @sstrubberg — Please resolve this issue and prioritize. 
@jeanservaas Please raise these types of issues before 4 months go by.

**Comment by jeanservaas** [comment]
@alisonjoseph @sstrubberg @mjabbink 

When this issue was prioritized and assigned to Vince. I assumed it would be treated like other custom tables/display components on the site (like on the type specs page, the icons page etc.) Not that we would just pull in a non-grid aware Carbon component like structured list. 

That's why I took the time to spec it's grid behavior at every breakpoint. Any time a designer does a comprehensive spec like  this—that's the intent. If it's not possible to achieve the redline, we need to raise a flag. It's never OK for something to look like this on our site and after years of beating the drum about grid alignment... all of our devs and designers need to be able to spot stuff like this and have each others backs in reviews. 

There was so much back and forth on the status indicator pattern just to get it up... it took far far longer than any of us anticipated, the research... the writing... the countless reviews and revisions, that I missed this grid misalignment in my final review... that's on me. But once that ship sailed, there was no picking it up again. 

The truth is that the designers are used to our issues getting dropped/deprioritized on this team. With v11 lasting, what, nearly two years now... @mjabbink what power do we have to prioritize an issue like this when our devs say it will push our major release further out?

**Comment by mjabbink** [comment]
I’ll put this simply. The spec above needs to be implemented. The gird alignment is quintessential to the system and it’s doable. It was doable 4 years ago when it was defined as such. It was doable even before that decision was made. If rebuilding is what it means well then rebuild it. We need to do this. It is a priority because it’s foundational. So much so, if some items from v11 need to be removed or delayed then so be it.

**Comment by jeanservaas** [comment]
Here are full red lines for the status indicator table component:

## Sketch file

[042721_CarbonPatterns_IconTable 2.sketch.zip](https://github.com/carbon-design-system/carbon-website/files/7540501/042721_CarbonPatterns_IconTable.2.sketch.zip)

**Comment by jnm2377** [comment]
> The truth is that the designers are used to our issues getting dropped/deprioritized on this team. With v11 lasting, what, nearly two years now... @mjabbink what power do we have to prioritize an issue like this when our devs say it will push our major release further out?

As far as I'm aware, devs didn't start working on v11 stuff until [this year](https://github.com/carbon-design-system/carbon/issues/7538). 

In our last retro, designers brought up that they're wrapping up v11 work, but devs actually still have a lot to work on, including docs. The truth is, we've haven't even had time to focus on v11 doc updates bc we still have a lot of features to implement. This is getting especially hard to try to get in on time with devs being down a lot of people. Ale is working on brand stuff, Vince was previously working on brand stuff but now he's leaving, TJ has been on leave, Scott is now a dev manager, which is great, but it means we're down another dev. And then we have a good chunk of devs working on Carbon Next and not v11 stuff.

This is a big reason why all the devs are asking to drop our brand support requirements. We've more than lost the "2 headcount" that is supposed to work on brand, and yet we still have to work on those things, which detracts from the actual Carbon work that we have (the whole reason we're on the team).

> I’ll put this simply. The spec above needs to be implemented. The gird alignment is quintessential to the system and it’s doable. It was doable 4 years ago when it was defined as such. It was doable even before that decision was made. If rebuilding is what it means well then rebuild it. We need to do this. It is a priority because it’s foundational. So much so, if some items from v11 need to be removed or delayed then so be it.

I disagree with this. This issue is just not a priority right now. It can and should be addressed, but it doesn't make sense for this to take priority over v11 things. v11 breaking changes are to bring quality of life updates to design and devs. Updated tokens, more accessible components, faster build times. While this grid misalignment may be a bug, it shouldn't take precedence over other things that will improve how our users build with Carbon. 

My other issue with this statement is that as far as I'm aware, devs have [communicated](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/682) before that we don't have grid alignment for any tables or table like components. It's not a new thing. We've said it before.

Lastly, "if rebuilding is what it means, then rebuild it" is not as easy as it sounds. We're refactoring a lot of components for better a11y in v11 and we're not even done with them bc it's not simple. And if we're talking refactoring components, then a11y 100% takes precedence over grid misalignment issues.

**Comment by mjabbink** [comment]
@jnm2377 Thanks for explaining some more details and I’m aware the dev team is still very busy and focused on v11. Nonetheless it’s  is helpful to know and further details of the efforts. 

A few things to clarify and happy to discuss further with the team. 

— The grid alignment is one of the ways how you deliver improved experiences to users. It’s fundamental to how things get designed and layered out in UI. Software and UI is primarily typography, information design, which includes the components and patterns. Grids and alignments are the means to organize information better and easier for users to navigate and interact with.  **It’s a priority for many reasons and at one point can no longer keep being deprioritized.**

— Dropping brand support means the 2 developers go away. The reason we added those folks the team is because the Brand team pays to have them do brand focused work der the Carbon teams’s management. That is why they support the brand team. If that DOU is removed we loose that headcount (2 developers). We have been lucky to have those two additional team members because we’ve also integrated them into solving Carbon issues as well. The Carbon team has also benefited from the relationship. I requested the DOU and worked this out with Robin a few years back.

— I did say all v11 comes to a stop. I’m suggesting a tradeoff of something so the custom component in Gatsby (outlined above) can be created. The custom component is one of those things the dedicated brand developers could tackle. That would be two full-time developers every week. There would be no affect on the v11 System team at all since those two people should have ever been factored in as available resources for v11.

 As far as recall I have not mentioned refactoring Carbon components above in this thread?

**Comment by jnm2377** [comment]
> It’s a priority for many reasons and at one point can no longer keep being deprioritized.

I totally get that. That's exactly why we want to drop brand work, though. If we no longer have devs like Ale & Vince (previously, Scott and myself) working on that, that's more people we can have working on Carbon specific things, whether that's docs or system work. 

> If that DOU is removed we loose that headcount (2 developers).

We've already lost that headcount. We can't keep saying that 2 devs are brand headcount when there's not enough design system devs. We're a design system team *not* a brand team. We have way less devs than when we agreed to the DOU and yet *more* work. We're tired of system work (whether it's design, doc or dev related) getting deprioritized too, and that's why this DOU needs to go away. Then the time spent doing brand work can actually go into issues like this. The best I can explain it is thru this diagram:
![Untitled_Artwork 5](https://user-images.githubusercontent.com/32556167/141860602-9125d083-11d5-4ffc-945f-44161684f4fe.jpg)


> As far as recall I have not mentioned refactoring Carbon components above in this thread?

You mentioned "rebuilding" which I assumed was in response to Alison's [comment](https://github.com/carbon-design-system/carbon-website/issues/2435#issuecomment-889402496) _"It would likely require a complete re-write of that component or a new one to be able to figure out a way to get this on-grid."_

Making our table components align to the grid would be an enhancement/refactor.

**Comment by mjabbink** [comment]
@jnm2377 — We have not lost that headcount because the DOU is still in place which supports the two full-time devs financed by the brand team. If that changes in 2022 that means the team likely loses those two devs. Of course we can pitch (and will) for keeping them if that happens but there are no guarantees that Doug or Katrina can make anytime soon unfortunately. 

> Making our table components align to the grid would be an enhancement/refactor.
I’m suggesting that work be done by AUX squad — that team that is already dedicated to the brand team (IDL, Gatsby). As I mentioned above, they should not be resourced for v11 work. AUX can do the refactoring work and it should not be hindering the v11 work at all. 

I’m not sure how this will play out yet but the Carbon for IBM.com team is coming over to the DPO. They will maintain their work to support the dotcom users and mission but since they have moved the needle from creation to now more support and maintenance they will likely be able to also contribute to the core Carbon team efforts. This will be a lot of what Alison, Scott, Jeff Chew, and Linda will have to explore.

**Comment by mjabbink** [comment]
I forgot to mention we hope to backfill Vince’s position/role. However, there is even a chance we may not be able to do that but believe me we will be fighting to keep that headcount.

We should take this to a Webex or Slack thread. I’m happy to get on a call with Alison and chat through this more with the team.

**Comment by alisonjoseph** [comment]
As a FYI the "aux" squad hasn't existed for a while now. We've been operating with Vince handling larger Brand issues/initiatives and the then other issues have been spread across the dev team for the two devs worth. With Vince leaving, Ale is taking the lead on Brand for now. Although this specific issue is a Carbon issue, not Brand, so not really relevant here anyway. Just wanted to comment since it was brought up above.

Josefina did a good job highlighting our lack of dev resources, we aren't forgetting about issues like these, it just isn't higher priority than everything else we have in our backlog. If this was a simple fix, it would have already been done. 

Let's continue this on a call or slack if needed Mike.
