### ISSUE TITLE
[Web Component] Icon card & search/filter bar

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#249]
Even though our new site is extremely fast, the new experimental iconography page still triggers a full page loading spinner overlay.

Is there a better way to handle this? Can we use skeleton states? Or even just remove the spinner overlay altogether?

![Screen Shot 2018-10-10 at 11.14.55 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/d0841aec-37ee-4d43-8bad-9bd0beb88270)

**Comment by joshblack** [comment]
@designertyler this detail was added since we had to switch to loading more icons. This was the stop-gap to help handle folks viewing this page on slower connections while we figured out a better way  👍 

From the technical perspective, can 100% implement skeleton states or anything else that is preferred!

**Comment by alisonjoseph** [comment]
Yep like Josh said, this was a first pass just to get all the new icons up there for people to view. There are SO many icons now might be worth exploring different ways to display/organize them.

**Comment by designertyler** [comment]
Thanks for the quick responses. This isn't a priority and only happens for a split second for me. A minor tweak could be to not overlay (and appear disabled) the nav and header. 

I'll create another issue for design to find a better way to organize/sort/filter the icons. That page gets pretty overwhelming.

**Comment by chrisconnors-ibm** [comment]
prior to nav changes can we lazyload/skeleton state these? maybe by row

**Comment by alisonjoseph** [comment]
Yea we could do skeleton state loading just depends on where this falls in our priority list. @joshblack how much effort do you think that would be?

**Comment by joshblack** [comment]
Do we have designs for the skeleton states? If they are minimal, shouldn't be too bad.

**Comment by shixiedesign** [comment]
Beta release nice-to-have: 
Icon card skeleton state. Making this part of the to-do under **[Web Component] Icon card**

**Comment by shixiedesign** [comment]
Icon Card spec
Sketchfile: https://ibm.box.com/s/o5qhcg064uzwedl63yimxh1hzx37kcn7
![image](https://user-images.githubusercontent.com/15144993/49815986-91234500-fd32-11e8-829e-0025f31f1eaf.png)

**Comment by shixiedesign** [comment]
# Final icon card design and spec
Sketchfile: https://ibm.box.com/s/o5qhcg064uzwedl63yimxh1hzx37kcn7
![image](https://user-images.githubusercontent.com/15144993/50427111-b5b80a80-0864-11e9-9d05-9f0127132b2f.png)
![image](https://user-images.githubusercontent.com/15144993/50427102-670a7080-0864-11e9-8d52-80c3bd51400a.png)

**Comment by jeanservaas** [comment]
We don't necessarily need all of this built right now but for launch can we:

- [ ] Take outside stroke off the component (should look like overview component in that the edges don't have a boarder

- [ ] Get rid of extra title (right now there are two lines of title (the name of the icon and then, what is supposed to be the copy and paste name for code... but the second one is not even correct... can we just take it out?) We can't do this in markdown because it is a component

**Comment by alisonjoseph** [comment]
This will be post-launch, but done next sprint.

**Comment by alisonjoseph** [comment]
https://github.com/carbon-design-system/carbon-website/issues/866

**Comment by shixiedesign** [comment]
Tracking icon stuff in a separate issue since minimal requirements of this issue achieved.
