### ISSUE TITLE
[tooltip] replace static images with gifs

### ISSUE THREAD

**Issue by johnbister** [carbon-design-system/carbon-website#2631]
### Usage

-Below are the proposed animations to include in the tooltip usage documentation.

This would replace tooltip_usage_1.png
![tooltip_usage_1_v2](https://user-images.githubusercontent.com/70543333/141164967-19b0d984-00ba-4962-b612-0c01a7b32d2c.gif)

This would replace tooltip_usage_8.png
![tooltip_usage_8_v2](https://user-images.githubusercontent.com/70543333/141164971-4600a916-b40d-42f5-9f3f-90b9fde918ed.gif)

**Comment by kingtraceyj** [comment]
looks good john! thanks for doing this. a few edits.

since tooltips are displayed only on hover or focus (the live demo is showing v10 and not v11—i need to open an issue for this), there would not be a focus state in the first image. it would only need to appear on hover.

since there is no mouse in the second image, i think that it would be fine to keep the focus state as if you were using a keyboard. but the focus state would remain active until focus away from the tooltip. so it should be present when the icon has focus and gone when there is no focus.

**Comment by johnbister** [comment]
no problem! here's v2 of tooltip_usage_1

![tooltip_usage_1_v2](https://user-images.githubusercontent.com/70543333/142068242-26370178-4ec9-4196-8513-5fd232586e6b.gif)

**Comment by johnbister** [comment]
and here's v2 of tooltip_usage_8.  let me know if you need any additional edits.

![tooltip_usage_8_v2](https://user-images.githubusercontent.com/70543333/142068693-39a7fc72-5f73-4e7b-9fd4-4f200411fc7a.gif)
