### ISSUE TITLE
[disclosure] replace static images with gifs

### ISSUE THREAD

**Issue by johnbister** [carbon-design-system/carbon-website#2632]
### Usage

-Below are the proposed animations to include in the disclosure usage documentation.

![disclosure_v4](https://user-images.githubusercontent.com/70543333/141166114-e733227d-3b69-4571-a0c8-598b48367915.gif)

![disclosure_profile_menu_v1](https://user-images.githubusercontent.com/70543333/141166104-d72df187-656b-455e-88bc-3c2e95cb224e.gif)

**Comment by laurenmrice** [comment]
The side toolbar disclosure gif looks great ! 🚀 ✅

---

**Profile menu gif**
Just three things, otherwise looks good:
- [ ] There should not be a divider to the left of the avatar when the menu is closed.
<img width="518" alt="Screen Shot 2021-11-10 at 2 05 31 PM" src="https://user-images.githubusercontent.com/43969356/141185840-2d2755f9-0b31-463b-ab04-6c95ed6c3502.png">

- [ ] There is a hand cursor in the background on the page that needs to be removed
<img width="560" alt="Screen Shot 2021-11-10 at 2 06 42 PM" src="https://user-images.githubusercontent.com/43969356/141185920-5be5c7b7-6a8c-42bc-b88e-18451ba98ce4.png">

- [ ] Once hovering inside of the menu, the menu item "View profile" should be the only thing that gets a hover color background change.
Ex:
<img width="705" alt="Screen Shot 2021-11-10 at 2 07 24 PM" src="https://user-images.githubusercontent.com/43969356/141186054-35f6d26c-c90a-419e-9fd5-ea193c3e4ca6.png">

**Comment by johnbister** [comment]
@laurenmrice thanks for the quick feedback!  

I think I addressed the 3 issues with the profile menu, but let me know if I missed something.  Thanks! 

disclosure_profile_menu_v2.gif
![disclosure_profile_menu_v2](https://user-images.githubusercontent.com/70543333/141818746-8dfdc5e6-1e4e-477d-878b-72af0390df2a.gif)

**Comment by laurenmrice** [comment]
Looks great @johnbister , thank you! ✅

**Comment by johnbister** [comment]
Here's v1 of the disclosure_combo_button gif. I have the menu sliding open like our dropdown, but this can be easily removed if the menu should just appear then disappear (with no sliding). 

In this particular case, would selecting 'Log artifact' in the menu change the primary button to 'Log artifact'?  Is that a unique function of this component that we want to show here? 

![disclosure_combo_button_v1](https://user-images.githubusercontent.com/70543333/142071277-6110331d-efb5-4bb1-bb7a-1565840c76a5.gif)

**Comment by laurenmrice** [comment]
@johnbister I like that it is sliding in as a dropdown. Once we make the component for this, we should remember to add in that animation. When you click  the"Log artifact" option, it won't change the primary button label, it will just perform the action. Looks good thank you!
