### ISSUE TITLE
Side nav breaks when browser width is smaller

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon-website#272]
## Detailed description

Side nav wraps "Your Product on IBM Cloud" on Chrome and Firefox. Seen on Clay's and DA's but not mine.

![image](https://user-images.githubusercontent.com/12533409/47031886-8e431400-d136-11e8-8454-67a012c07bb5.png)

![navbug](https://user-images.githubusercontent.com/40970507/47031191-014b8b00-d135-11e8-9bc7-9cda3b951ab7.gif)

Looks like inline styles are being applied at the smallest breakpoint causing existing styling to be overwritten and break.

**Comment by asudoh** [comment]
@alisonjoseph Stumbled at this issue, seems that the website has responsive type. Wondering if it makes sense for side nav - Thoughts? Thanks!

**Comment by alisonjoseph** [comment]
@asudoh I think the larger font size does make sense for mobile I checked on my phone and I think it would be too small otherwise. 

This issue was created when I added a height to each item recently to make them all 32px I believe to match the design language site. Should be able to fix that without having the set height. 

![image](https://user-images.githubusercontent.com/2753488/47219685-19a9e880-d375-11e8-88a2-a85ae05bae77.png)

**Comment by asudoh** [comment]
Cool thanks @alisonjoseph for sharing your thoughts! Sounds what we are going to do is good enough for now.

Some future thought - Is the larger font in phone for avoiding miss-touch? Or is the font look smaller in phones than one in desktop? Basically wondering what should happen for tablets.

**Comment by alisonjoseph** [comment]
closing this since it is a non-issue in new site redesign.
