### ISSUE TITLE
Data table use case 

### ISSUE THREAD

**Issue by leegracee** [carbon-design-system/carbon-website#2761]
## Summary
We have a use case in a scenario when a data table is on the bottom half of a page and when there is not many table rows. If a user were to open an overflow menu, it gives off an awkward visual of the menu being cut off and user having to scroll in the very tiny container the data table is in. This interaction is not necessarily violating any Carbon guidelines, but the design team do agree it's unusual. 

![usecase](https://user-images.githubusercontent.com/89665807/156435201-e1914e47-be69-454a-b504-81eb4471d462.gif)

## Relevant information
The [storybook](https://react.carbondesignsystem.com/?path=/story/components-datatable-toolbar--with-overflow-menu) shows the overflow menu is following that it is overlayed on the data table, but what happens when the data table's height is so small? Is there an official padding we can use to avoid this?

**Comment by tay1orjones** [comment]
In this case, one thing that may help is having OverflowMenu open upwards instead of down. You can give OverflowMenu a `direction="top"` prop to configure it to behave this way.

On a bigger scale, I'd consider looking at how to reproportion the page to ensure the data table has a taller height to avoid this issue altogether.

Going to close this for now, but let me know if there's anything else I can help clarify.
