### ISSUE TITLE
[Pages] Homepage Design - Carbon X Website

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#292]
Designs for home page improvements for v10

Steps to complete:

- [x] Gather requirements
- [x] Create designs

Current feedback:
Surface articles and news.
Examples of carbon applied.
Feature new components.
Reference back to language?

**Comment by designertyler** [comment]
Feedback based on Ben Hansen's research for Digital. Some insights apply directly to Carbon an some don't. Great to keep in mind for the redesign. https://ibm.ent.box.com/s/wqz7rsweau3bzcz1dfudv93qbh7zkq01

- [ ] Clearly  state the  site purpose in a couple  of sentences above the fold. It needs to include “standards” and code-base relationships/roadmap.
- [ ] Separate “What’s new” from “Getting started”, clearly include #1 above in What’s new, and add a Getting started page that  begins with templates  and step-by-step instructions.
- [ ] 3.Update IA  and content  for  supporting sections. 

- [ ]The message of the home page, introducing the site, is missed or poorly understood from the beginning, and doesn’t really improve with reading. "Most users never see the introductory note at the top..."
- [ ]Add a phrase like “formerly the Northstar design system” to the leadspace and define migration paths.
- [ ]Address the need for a “getting started” page, consider rewriting “What’s new” to focus on system migration (and it may be a temporary page), and consider moving releases to a focused page, perhaps with the lower nav options.
- [ ]Eliminate “fluffy” language – everywhere.

- [ ]Reduce the height of all lead spaces, reduce scrolling, and reconsider the dark black background.

**Comment by designertyler** [comment]
**IN PROGRESS - NOT FINAL**
Here are some sketches and notes on the homepage progress. These are option I explored based on Ben's research from digital, Carbon feedback, new functionality, new shell and language. @jeanservaas was also going to push the design to explore other options.

I started with the base layout similar to what [Digital](https://w3.ibm.com/design/digital/) has today and how our component pages are laid out. This made the component and home pages too similar and didn't give a compelling home page. 

![screen shot 2018-11-13 at 9 45 08 am](https://user-images.githubusercontent.com/19270502/48424739-d7cc5200-e728-11e8-9f57-216071922f34.png)

The /design and Language pages use the lead space for the main calls to action or feature rather than simply labeling the page. I pushed forward with this approach since it's also what the current Carbon site does with this space and Ben's research recommends addressing the first question that pops into people's heads when visiting the redesigned site, "what happened to the old thing I knew?" 

Here's the lead space with the CTA to learn about what happened to the carbon name and how it's an implementation of the new IBM design language. [Link would go to this page](https://www.carbondesignsystem.com/about/design-language)

![screen shot 2018-11-13 at 9 46 09 am](https://user-images.githubusercontent.com/19270502/48424957-7062d200-e729-11e8-815a-cbadabd59549.png)


I had a quick chat with Ryan and the work he was doing for /design and how it incorporates a lot of large images. Language also does this.

That approach didn't seem to work when applied to the system site. We do have a visual style that is unique to system and that is the redlines and grid used to markup our component examples.

I explored some options abstracting components in this style and applying them to a dot grid texture in the lead space. 

![screen shot 2018-11-13 at 9 50 11 am](https://user-images.githubusercontent.com/19270502/48425544-ab193a00-e72a-11e8-8acc-22fa45a08e4d.png)


It seemed to fight for priority with the main CTA and needs more exploration.

![screen shot 2018-11-13 at 9 59 13 am](https://user-images.githubusercontent.com/19270502/48425663-e74c9a80-e72a-11e8-9516-7646e408ba07.png)
![screen shot 2018-11-13 at 9 59 19 am](https://user-images.githubusercontent.com/19270502/48425664-e74c9a80-e72a-11e8-9b1d-f61e83ffb89c.png)
![screen shot 2018-11-13 at 9 59 27 am](https://user-images.githubusercontent.com/19270502/48425666-e74c9a80-e72a-11e8-9593-82ce9783e237.png)


![screen shot 2018-11-13 at 9 59 56 am](https://user-images.githubusercontent.com/19270502/48425939-69d55a00-e72b-11e8-9f03-04ca384a65cc.png)

I've been sketching with the black dot grid in the meantime and it's actually growing on me...

![screen shot 2018-11-13 at 10 00 41 am](https://user-images.githubusercontent.com/19270502/48425955-6fcb3b00-e72b-11e8-9d56-a1a37149092d.png)

One thing that stands out from this layout compared to Language and /design is the use of gutters. I went with this direction to make the jump to the new language less jarring to people familiar with the current Carbon site and to keep the "practical, daily use, documentation" feel that get's lost with the more expressive layouts. Feedback welcome around that.

There are a couple instances of the markup/redline used as visuals. 

Compared to current homepage:
- Getting Started is broken out by designer and developer. Currently there's a single getting started tile that defaults to designer.
- Guidelines is removed. Currently there is a single guidelines tile that defaults to Accessibility. it would be nice to bring this tile back to the home page or break it out by the individual categories like getting started.
- Components keeps its tile and it given more importance. This is the most visited page based on analytics.
- Resources are broken out individually React and Angular libraries are grouped. This section feels weak and needs some feedback/iteration.
- Included latest articles under "Latest" category.
- Contribution CTA is weak and needs iteration. would be nice to work on the message here.

![homepage_sketch](https://user-images.githubusercontent.com/19270502/48426226-eff1a080-e72b-11e8-9984-98e66a65108b.png)

**Comment by designertyler** [comment]
Updates based on feedback from design session

- Darker lead space card
- "Components" type is scaled down.
- Designers and developers are changed to "Start designing" and "Start developing"
- 1 px space between resource cards.
- 1 px space between "Latest" cards
- Corrected spacing and added redlines.

![homepage_sketch](https://user-images.githubusercontent.com/19270502/48495748-44615280-e7f6-11e8-8cdd-046cdb1e7684.png)
![homepage_sketch_measure](https://user-images.githubusercontent.com/19270502/48495755-49260680-e7f6-11e8-9a7f-557db741780e.png)

**Comment by claycrenshaw** [comment]
Looking good! I would still love to see the actual substantive content (e.g. getting started tiles) start a little higher up on the page, above the "fold." Also would be great to see what other types of content would fill that top space once the "Carbon is now called  _________" content is no longer relevant.

Any thoughts on how we might dynamically integrate the latest "what's new" content into this page? Maybe it can take the place of one of the "Latest" tiles?

The width of the text columns (like under the "Component Libraries" header feels oddly narrow to me. . . Seems like a couple more grid columns of width for that text block might make the page feel a little less choppy.

IMHO this page is already miles ahead of what we currently have. :)

**Comment by alisonjoseph** [comment]
just a heads up that anything divided by 3 like that won't be on the grid. (I can set to 33% width if needed)

**Comment by claycrenshaw** [comment]
To me, this layout is starting to feel a lot like a marketing page, with the big hero image and big intro paragraph. It's a nice looking marketing page, but I'm not sure that's the approach we should be taking with our homepage. We are requiring the user to scroll before getting to any utility within the page, which is not ideal. Our users come to Carbon to get their job done, and I think that putting so much "fluff" on the page is not serving them well. I'd consider exploring some more abstract, graphical stuff instead of the photo, and think about how we can shift more of the "meat" above the fold. Also, per our convo with Daniel yesterday, I think we can still prominently call it "Carbon" on the landing page (rather than a small "formerly known as. . ." treatment.

I think we should also be sure to account for how this page will scale to different widths. What does it look like at 640 and 1440?

We had discussed including some kind of space for "what's new?" content on the homepage as well. Kind of a peek at the latest updates, with a link to the changelog.

I wonder if the Getting Started callouts really need to span the whole width of the page, or if they might sit better side by side (like in Tyler's earlier explorations). Having what is essentially a link take up this much space on the page feels a little out of scale to me.

I'd also consider adding a line of supporting text to each of the tiles in "Other Resources" to help clarify what that link actually is. It's a little obscure with just the title, and we have the space to clear that up a bit for the user.

**Comment by alisonjoseph** [comment]
+1 on needing to know how it scales down

**Comment by jeanservaas** [comment]
OK just so everyone knows that we've been shopping this around to other teams... this one is Mike Abbink approved at least design wise (link's been updated in box):

- I think we should commit to a photo banner and try to get product UI in at light theme for v10.

- ps @alisonjoseph I'm showing the designs on the grid below, as I understand from @joshblack the nav doens't affect the grid but goes browser wide

![home_desktop dark_v2](https://user-images.githubusercontent.com/43144260/49171566-6a154e00-f304-11e8-9f30-9d7a45077d4d.png)

![image](https://user-images.githubusercontent.com/43144260/49172123-c88efc00-f305-11e8-9504-82f9d8276776.png)

**Comment by alisonjoseph** [comment]
The grid should not include the nav, discussed w/ @designertyler, @joshblack and referenced the documentation we have on grid and grid influencers.

**Comment by designertyler** [comment]
I'd still prefer finding an alternative to the photo and agree with Chris about featuring a UI that cannot be built with the current components.

The simplified components in the latest mockups are moving in the right direction. I really think that could evolve into something of a system visual language. 

I agree with Clay's comments, but not sure this layout crosses the line of being too expressive for productive daily use. I think we can have a little leniency on the homepage for that if the rest of the site is focused on productivity. 

Ben Hanson did a usability study with the Digital site and even though it's focused on their site, a lot of the insights apply to us. https://ibm.ent.box.com/s/wqz7rsweau3bzcz1dfudv93qbh7zkq01

**Comment by shinytoyrobots** [comment]
What is the purpose of these dots (including the highlighted one)? It implies a slider.
![image](https://user-images.githubusercontent.com/825457/49256481-c9528b80-f3f4-11e8-800f-ceab5b24503a.png)

Also - we are saying "IBM Product Design" in top left, and "IBM Produce Design System" in main content. Do we want to match these?

**Comment by claycrenshaw** [comment]
I was wondering that too :) Is this a carousel?

**Comment by aagonzales** [comment]
**Sprint 25**: Finalize homepage design. @jeanservaas or @designertyler set up meeting for final review and decision. Include dev for scope.

**Comment by jeanservaas** [comment]
### FINAL HOMEPAGE

https://ibm.box.com/s/589knwzwuxkuj850ev137f2fka0p7taf

Sat with @designertyler and weighed all of the actionable feedback:

- We will keep the banner image but reskin the screen with new artwork (I will provide mild to wild options)

- I ditched the "carousel dots" on the banner @shinytoyrobots (those are gone)

- I fixed the horsey link at the bottom, in the Contribution section and styled it to match the links on the IDL site

- Get help from @claycrenshaw on that top copy intro'ing v10

![homepage_final](https://user-images.githubusercontent.com/43144260/49404759-fa450000-f715-11e8-91da-ccfa172a6d04.png)

**Comment by claycrenshaw** [comment]
Revised homepage copy. Thinking less is more in this case, since we cover all the IDL, etc. stuff in "Getting Started".

![image](https://user-images.githubusercontent.com/20912642/49657467-5ef9a680-fa05-11e8-9856-d3767bba58db.png)

**Comment by claycrenshaw** [comment]
@alisonjoseph @jeanservaas ^

**Comment by jeanservaas** [comment]
Could we get a little more here? @chrisconnors-ibm  If that's the max content we can get here we'd need to rethink the design, which I'd really like to avoid at this point. If I'd known content would be that minimal I'd have considered folding it into the header or something... the idea is to visually match the top band with the bottom band. 

I also don't think it's a problem if we surface some of the getting started content on the homepage too.

**Comment by claycrenshaw** [comment]
I am definitely not clear whose call this is. . . probably not mine! I'm just suggesting what seems like the appropriate amount of messaging to me for that space. If you guys want to use my whole paragraph from About Carbon, I'm sure that would work fine. Might be a little heavy for the returning user, but I guess that's just a tradeoff.

**Comment by jeanservaas** [comment]
Cool I will try we that and see where we land. For now that should work fine!
