### ISSUE TITLE
Tutorial Support

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3000]
The tutorial is generating a lot of bugs for users. We need to explore what we can do to minimize or reduce these so we can focus on sprint work.

Ideas:

- Chat with Rosno about how the badging process works.
- Remove PRs from the badging process.

**Comment by jnm2377** [comment]
It seems to me the goal of our tutorial is to teach people how to use our assets, and we still achieve this without submitting a PR. It feels like we got a little ambitious and tried to teach a lot of general dev things — CI checks, graphql, testing, GitHub, PR submissions, deployments — and end up having to debug or teach things that aren’t related to our ultimate goal: how to use Carbon.

Some of the reasons why I think this would be a good idea:
- We don’t have the bandwidth to make tutorial another thing we maintain and support (it’s clear by our lack of prioritization)
- It makes us look bad when we don’t pay attention to the PRs that are failing and people get frustrated
- Given our backlog discussions we’ve had recently, it feels like we can be realistic and say: the PRs aren’t a priority. But teaching people how to build with Carbon is, and just building the tutorial does that.
- These PRs aren’t a contribution so it doesn’t feel like it’s worth debugging someone’s PR for the tutorial (different, however, than helping debug actual tutorial issues) given all the other work/support we have to do
- We have people with a wide range of dev experience do this tutorial, and some know a lot and can easily debug and some need their hand held and it’s time consuming
- This would mean one less support item for us (partially, since there are other tutorial issues people might have)

This issue is not just related to the v11 update. We've been having issues with the tutorial even in v10.
🟦 : v11
🟥 : v10 - old PRs
<img width="660" alt="Screen Shot 2022-06-17 at 11 20 05 AM" src="https://user-images.githubusercontent.com/32556167/174339363-0e307370-a50d-4fcc-830d-0578cfa207da.png">

And we've had people successfully open v11 PRs.
<img width="353" alt="Screen Shot 2022-06-17 at 11 21 37 AM" src="https://user-images.githubusercontent.com/32556167/174339625-18de891a-d423-497f-a198-37cb306709f0.png">


One thing to take a look at would be **_how can we make our badging process easier so that it doesn't require PRs**?_ I think this is possible. Maybe requires taking a look at how other badges are working. I know when I got my EDT badge it was more of an **honor system**, where the "proof" to get the badge was writing up some sort of paragraph about our experience.

**Comment by sstrubberg** [comment]
Hey @jnm2377, thanks for the write up and articulating what's going with the Tutorial along with some ideas on how to move forward. Before we go and make any sweeping changes to the tutorial, I'd like to understand more on a couple of things surrounding these failing PRs.

- What changed in our tutorial that is making so many PRs fail all of the sudden?
- How long has this been going on?
- Is there anything we can do to make the PRs succeed more?

Let's put some time on the calendar to flesh out this issue more and get more alignment :)

**Comment by tw15egan** [comment]
FWIW a lot of tutorial errors are user-error (not following instructions exactly, modifying package versions)

**Comment by jnm2377** [comment]
>What changed in our tutorial that is making so many PRs fail all of the sudden?

@sstrubberg This is what I was trying to relay with the screenshot and the explanation. These failing PRs aren't sudden. It's been happening since v10. I think on the team, we've just been paying attention to it lately bc Ale and I were working on migrating the tutorial, but we just haven't had the bandwidth to pay attention to these PRs considering everything else we maintain.

**Comment by jnm2377** [comment]
>Is there anything we can do to make the PRs succeed more?

@sstrubberg I think what TJ said it on point: a lot of tutorial errors are user-error. And like I mentioned [here](https://github.com/carbon-design-system/carbon-website/issues/3000#issuecomment-1159046239) there are a wide range of skilled devs who do this tutorial, some need more hand holding than others. It's evident that our tutorial works by the PRs that have been approved and closed, but for the ones that fail, generally, unless they can debug on their own, it means we have to debug with them or for them, which takes time.

**Comment by joshblack** [comment]
@jnm2377 would it help at all if we had either a comment with an FAQ (if it fails) or changed things that are causing to fail when it might not need to?

Some things that came to mind could be:

- Using the offline cache / immutable installs for yarn, could simplify with `npm`
- Formatting: could remove this as a check but leave it as something you can still run

Unfortunately, I think the tests would have to still be included given that they are what is checking the functionality.

Here's a quick recap of the most recent failing PRs:

- Where: step-5, what: failed to find manifest for CF
- Where: step-2, what: yarn lockfile
- Where: step-2, what: yarn lockfile
- Where: step-2, what: yarn lockfile
- Where: step-1, what: yarn offline cache
- Where: step-3, what: yarn offline cache
- Where: step-3, what: yarn lockfile

**Comment by jnm2377** [comment]
Update: the proposed solution for the time being is to create an FAQ for issues that pop up a lot, and see if it reduces the need for support. Will close this issue for now, and open an issue to track adding the FAQ next sprint.
