### ISSUE TITLE
Design/Dev for page layout - Carbon X Website

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#303]
Need design specs for basic page layout for Carbon X

Header
Tabs
h2
h3
h4
intro paragraph `<page-intro>` _component currently_
paragraph
list
footer 

@designertyler feel free to break any of this out in to separate issues if needed.

**Comment by joshblack** [comment]
@designertyler one thing I'm curious about is the difference on the site for pages that are for documentation versus for editorial moment. If for the docs use-case, do we use the product or editorial styles? In addition, would that change things like headings (where Title currently is) from a more open layout to a dense one.

**Comment by eraymond25** [comment]
To Josh's point I think that there are definitely different intentions for different pages and we need to update aspects (especially the leadspace) to cater to those different style pages.

Regarding leadspace designs I think they should be using the editorial typescale and we're implementing 3 different leadspace templates into the Digtial site -- small, medium and large (we can call them something else if you prefer) to be able to tackle the site pages that are more introductory (could use large) and site pages that are more documentation (could use small). We don't have specific rules on when to use which one, but would like to get them eventually.

See our Digital task here:
https://github.ibm.com/webstandards/digital-design/issues/162

**Comment by designertyler** [comment]
Update on page layout using [the checkbox page](https://www.carbondesignsystem.com/components/checkbox/code) for content. Feedback and comments welcome!

One thing I'm thinking about changing is the width of the Code window. I'd like to make it full width.

![page_layout](https://user-images.githubusercontent.com/19270502/47736048-cd478e00-dc3b-11e8-99ec-bd3669ff6122.png)


![page_layout_measure](https://user-images.githubusercontent.com/19270502/47736056-d173ab80-dc3b-11e8-96c3-bf766ec40866.png)

**Comment by eraymond25** [comment]
shouldn't the checkbox itself be left aligned? It feels like that is the only piece not aligning to the grid.

**Comment by alisonjoseph** [comment]
Will also need the field-01/02 toggle for some components
![screen shot 2018-10-30 at 1 35 34 pm](https://user-images.githubusercontent.com/2753488/47741624-b6f3ff00-dc48-11e8-9e5b-ed0df823f705.png)

**Comment by jeanservaas** [comment]
Hey @designertyler, there's another version of that black top banner (the shorter one) that doesn't have that intro paragraph on it (@eraymond25 made it). 

We were talking about it in the Connors meeting today. That type is better suited to larger fields — it seems a bit grand when you're using it on a smaller banner. We also may not always have appropriate content for that paragraph in v10.

**Comment by designertyler** [comment]
Thanks for the feedback everyone!

@eraymond25 The components are centered within the code examples on the current site and I stuck with it because it works for all the different sized components.

**Centered:**
<img width="1039" alt="screen shot 2018-10-31 at 7 08 11 am" src="https://user-images.githubusercontent.com/19270502/47787168-01728b80-dcdc-11e8-8506-03284360581a.png">
<img width="975" alt="screen shot 2018-10-31 at 7 06 44 am" src="https://user-images.githubusercontent.com/19270502/47787175-06cfd600-dcdc-11e8-9fd1-c0148fe8d569.png">



**Left aligned**
![screen shot 2018-10-31 at 7 06 44 am2](https://user-images.githubusercontent.com/19270502/47787197-16e7b580-dcdc-11e8-98a4-cf9f59e6858b.jpg)
![screen shot 2018-10-31 at 7 08 11 am2](https://user-images.githubusercontent.com/19270502/47787198-17804c00-dcdc-11e8-8ead-2e7e40e7fc8b.jpg)

@alisonjoseph I mock that up. I think the component example will need a few more rounds. I don't think it's quite there yet.

@jeanservaas I'm sold. I wasn't sure how that type of lead space would work for our site. I'll move that below.

**Comment by designertyler** [comment]
Here are the revisions with the field toggle in the component example, display-02 for the title, updated footer and shell to the latest, added next and previous buttons.

I kept the intro sentence at the top in the lead space. In the future we may have longer or better intro paragraphs for our components and more space, but right now the intros are all sentence length. 

![product_page_layout_20181101](https://user-images.githubusercontent.com/19270502/47873505-62cf5300-dddf-11e8-83fd-5e55156457db.png)
![product_page_layout_measure_20181101](https://user-images.githubusercontent.com/19270502/47873510-65ca4380-dddf-11e8-9d65-98d4f9ecf7ac.png)

**Comment by alisonjoseph** [comment]
Looks good, I have some questions about how the grid should be set up, and how/why some elements start in the middle of a column etc.

**Comment by joshblack** [comment]
@alisonjoseph starting next week we should be doing some grid-related elements work and I bet it'd be helpful for all of us to get onto the same page for this kind of stuff.

**Comment by designertyler** [comment]
vertical spacing specs here https://github.com/carbon-design-system/carbon-website/issues/467#issuecomment-442978521
