### ISSUE TITLE
Global header pattern

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#328]
**Abstract**
Pattern describes global UI element (header) and its application for product and system level tasks. Foundational entry for broader navigation patterns; some topics will be referenced for future authorship. 

**Link to preview:** 
This preview link reflects the latest changes up to 11/19
https://carbon-website-git-fork-designertyler-navigationpatternreview.carbon-design-system.now.sh/patterns/global-header

**Next steps**
- [x] Peer review / early SME review
- [x] Chris Connors' review
- [x] Image review (Jeannie)
- [x] Content review (Jan)

Current Carbon pattern:
https://www.carbondesignsystem.com/experimental/navigation-pattern/

IoT:
https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/patterns/in-application-navigation/overview/

WH:
https://pages.github.ibm.com/Watson-Health/components/navigation/overview.html

- [x] Do we need to distinguish between the horizontal and vertical nav patterns outside of the Shell component usage tabs?
- [x] Update images to the latest production guidelines.
- [x] A11y considerations: DOM order and "[meaningful tab sequence](https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html)", https://www.w3.org/WAI/WCAG21/Understanding/consistent-navigation.html
Landmark regions https://www.w3.org/TR/wai-aria-1.1/#landmark_roles
https://github.com/carbon-design-system/carbon/issues/3991
- [x] Grid influence (sync with the latest grid guidance)
- [x] Add relevant references
- [x] Move the existing navigation pattern to production
- [ ] Touch input
- [ ] Do's and Don'ts
- [ ] Create header links with submenus
- [ ] Add examples for each type of organization schemes
- [ ] More content organization schemes: task
- [ ] Considerations for translating navigation for right to left languages.
- [ ] Hierarchy and placement of information

Update Shell guidance for:
- [ ] login and authentication
- [ ] actions in the header
- [ ] Logged in vs. Logged out experience: how is the logged-in vs logged out experience different
- [ ] Icon number and status badges
- [ ] Updated UI Shell left panel usage, sandbox demo, and style to include UI shell rail.

**Comment by designertyler** [comment]
This preview link reflects the latest changes up to 11/19
https://carbon-website-git-fork-designertyler-navigationpatternreview.carbon-design-system.now.sh/patterns/navigation

**Comment by jeanservaas** [comment]
Finally got a chance to sit down and go thru! Couple things:

- This is Jan's lane, but on first glance, the H2 "Terms" kind of threw me off... it made me think of "terms and conditions" ... maybe even just saying "common terms" or something more to contextualize it.

- This guy may benefit from going full width with the table
![image](https://user-images.githubusercontent.com/43144260/69212499-20320300-0b27-11ea-8e1d-fa9bde59bdf2.png)

## illustrations

I made a sketch file (attached below) with assets in it just so we start to do these things in a very consistent manner... including streamlinging things like color, browser, margin... how we denote images and how we denote type in this reductive, illustrative style.

For instance in these image illustrating header and side panel nav, there's a lot going on, the gutters are not the same size as the margin bottoms and some of the images are odd sizes. Also, the color scheme is a kind of gray on gray that we don't really use in product.

![image](https://user-images.githubusercontent.com/43144260/69212834-004f0f00-0b28-11ea-9bc0-41ad2a82dfb1.png)

I took a pass at simplifying some of this (included in the file); if you want to tweak, you can just use this as a base:

- Some options for "Header only" image

![image](https://user-images.githubusercontent.com/43144260/69212961-5ae86b00-0b28-11ea-8dbb-3539f1920b2b.png)



- Some options for "Left panel example"

![image](https://user-images.githubusercontent.com/43144260/69213034-94b97180-0b28-11ea-902c-4bc6e2251754.png)


- Some options for "Left panel example"

- Some options for "global examples" (i didn't touch the tree diagram... i think that's fine)

![image](https://user-images.githubusercontent.com/43144260/69213110-ca5e5a80-0b28-11ea-90d8-8606bd81f253.png)

## Callouts 

- For the callouts, I used a 24px circle, since these images get really small with the diagram and even at the 8 column full size. I also used a 14px semi-bold all cap for the letter and Magenta 60; Teal 40... the teal 50-60 to me looses the acid and the pop that i associate with annotations; The stroke weight is 1.5px — I also detached the circle slightly from the line to give it a little air.

_(I'm leaning toward full saturation on the call outs, I was using the tints for sub-callouts in my button guidance; I also did a few more sketches... maybe we should share these with the channel one last time... i'm going to run them by Mike again tomorrow so we're all using the same thing)_ 

This is by NO means exhaustive... just a few sketches of things I've seen... but especially for your examples... I think the outlines are going to work better than anything else.

![image](https://user-images.githubusercontent.com/43144260/69213526-fe864b00-0b29-11ea-8bb2-99d9ae01ab03.png)

## Other images

- I thought we were going to explore product options for these real examples instead of /design and carbon docs site... is that because no one's using the shell in product without serious alterations?

![image](https://user-images.githubusercontent.com/43144260/69213641-4c9b4e80-0b2a-11ea-878d-edfaefa2222c.png)

Even if you do use /design for this one, which I think is OK, the magenta on magenta along with all that line work in the image is distracting... I think using the really bold simple homepage would be so much less distracting

![image](https://user-images.githubusercontent.com/43144260/69213952-39d54980-0b2b-11ea-8c15-0359b7e87335.png)

- For this the landmark region image I'm also wondering if we can use something more exciting and also try a few things like this... If we have to use a Gatsby site, I'd probably look for something other than Carbon, since you have that other image using the Carbon homepage... but I think something like this looks a lot better that that docs page with really small content on it. (Here I made the outline really pop by giving it a 2px stroke. 

Also always use the same browser top. I added the dark gray one in over what you ... you have the correct one in the /design image but not this one.

![image](https://user-images.githubusercontent.com/43144260/69214525-cf250d80-0b2c-11ea-8446-8b946f655672.png)


- again put this image in that same browser like everything else; i've also noticed... I think you have three images from the carbon site (two from the homepage and one from the interior) then /design is the only other site you use... i mean, ideally this would all be product, but if we can't, I'd probably go ahead and try to use nice images from 1) /design 2) maybe the ai site 3) brand center? or the IDL site... Pete also has some really nice light theme screens from a gatsby site he was working on that used the Serif... just need to change it up.


![image](https://user-images.githubusercontent.com/43144260/69214784-75711300-0b2d-11ea-956e-93b3dcf93590.png)

[illustrations_for_tyler 2.zip](https://github.com/carbon-design-system/carbon-website/files/3867658/illustrations_for_tyler.2.zip)

**Comment by designertyler** [comment]
Good feedback! @jeanservaas 

I updated the images in the PR, changed it to "Common terms", and expanded the task example matrix to full width. I don't know if I'm sold on the wider layout for this one, but let me know what you think. 

![image](https://user-images.githubusercontent.com/19270502/69256052-78e0ba80-0b7e-11ea-9cad-8cbca4633d61.png)


### Callouts

> For the callouts, I used a 24px circle, since these images get really small with the diagram and even at the 8 column full size. I also used a 14px semi-bold all cap for the letter ... The stroke weight is 1.5px ...

In the work file, you attached the circle is 20px and the stroke widths were 2px. I'd like to keep using whole pixels for strokes so they're as crisp as possible and can update the circle size to whatever we decide on.
![image](https://user-images.githubusercontent.com/19270502/69258296-04a81600-0b82-11ea-923e-dfec370b0535.png)

At 14px the semi-bold numbers are 9px wide but the letters vary. What about using mono-space? That way when we make the callouts Sketch symbols there won't be any wonky alignment when we override the value to another letter.

Using mono 14 would give us a consistent 9px no matter the character.

> I thought we were going to explore product options for these real examples instead of /design and carbon docs site...

Yep, I updated the ones at the top and forgot to do the ones lower on the page. They're all updated to be the abstract representations of product.

**Comment by designertyler** [comment]
Feedback from Maui and Alex:

- [ ] Is there a way to add an accompanying visual to the task matrix?
- [ ] Reiterate some of the terms into the configuration sections while explaining some of the reasons you'd use one vs. the other.
- [ ] Do's and Dont's for the different configurations. "When you're using this... don't do..."
- [ ] The "Navigation" section title feels weird since the whole pattern is navigation. Maybe try Information architecture, anatomy, structure...?
- [ ] Add back in the "Global, Local" labels to the exhibit images. 
- [ ] Improve the correlation of the ABC's. Is there a way to add the letterns back into the abstracted screens?
- [ ] Show a global nav w/ just left nav and header in one image. (sketch in notebook)

**Comment by designertyler** [comment]
The additional section for header utilities will not be included for the 12/5 review.

The current outline for that section:
## Header utilities (WIP)

The header gives a home for global system-level utilities from anywhere in the site. 

Utility icons should not be used to directly navigate to an area. Instead, they should open a panel that gives a summary and then can link to where you can view more.

![header-utilities](https://user-images.githubusercontent.com/19270502/70274378-ada16400-1771-11ea-8aaa-a6599e842942.png)

### Search
- Global search
- More guidance around search can be found in search pattern.

### Docs & support
Link to relevant resources like docs, tutorials, support contact information. Try to make the resources contextual to the topics of your user's current location in the site.

### Notifications
Lets the user see when a new notification comes in, review it, and then jump to a location to take action and resolve.

### User profile and account
System-wide user settings

### Authentication

### Switcher

**Comment by designertyler** [comment]
Chris's feedback cont.

- [ ] Global definition changed to clarify
> "A global UI element is preset everywhere in your UI. It contains system and product items your user may need at any time: navigation, authentication, notifications, and more. Global elements remain consistent from one context to another."

- [ ] Change "process" back to "task"

> Task hierarchy
The task hierarchy describes the breadth of effect for various tasks. For this guidance we use the term “product” to encompass the broad category of products, applications, offerings, or web properties.

- [ ] Remove the "matrix" title

**Comment by designertyler** [comment]
Diana feedback:
They are using the left nav for global nav and tabs for local. By showing the different products and location's (parent and child) within the products in one view allowed the user to easily move between them when completing a task – stringing products together. This is common for their user.

This is not easy with the current implementation of the UI Shell. It would require additional steps of opening the switcher, clicking the product, and then clicking the area in the product. 

- [ ] Is this acceptable, how can we accommodate their need to have their user quickly pivot around the site to complete the task?

- [ ] More do's don'ts. Having visuals helps explain the concept.

- [ ] In the drill-down example we show the D not appearing in the left nav. Make it apparent that we don't want 3 nested levels in the left nav. This is a possible do don't.

- [ ] Link to the breadcrumb component and add links to other relevant components.

**Comment by designertyler** [comment]
Closing this original issue.

Remaining feedback and changes will be tracked in the v2 issue here https://github.com/carbon-design-system/carbon-website/issues/765
