### ISSUE TITLE
Select field option list browser default vs dropdown

### ISSUE THREAD

**Issue by Po4** [carbon-design-system/carbon-website#3290]
Why does the select field use the browser default as option list and not the custom option list from the Dropdown component?

<img width="543" alt="image" src="https://user-images.githubusercontent.com/14204117/204783653-089115e4-d661-49b0-b486-3b6491805263.png">
<img width="369" alt="image" src="https://user-images.githubusercontent.com/14204117/204783747-e8848cd0-da31-450d-98ff-a117bee9c47b.png">

https://carbondesignsystem.com/components/select/usage/#live-demo
https://carbondesignsystem.com/components/dropdown/usage/#live-demo

**Comment by tw15egan** [comment]
Select menus are notoriously tricky to style via CSS, as each Web Browser implements them differently. When we created the `Select` component, we avoided trying to override these styles and left them as defaults so that we did not break the out-of-the-box form element compatibility that comes baked in with the browser native `select`.

If you open the `Select` in Edge, Chrome, Firefox, and Safari, you'll see four different menus. We could not satisfactorily align the styles across the ever-changing implementations, so we've left them untouched. That way, it will render consistently for users expecting to see their browser of choice default `select`. 

`Dropdown` was created to create a cohesively designed select element; it's just missing some of the "built-in" accessibility and form verification/functionality a `select` has by default. Hope that helps clears that up!
