### ISSUE TITLE
Add "who can use Carbon" to FAQ section

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#33]
@aagonzales commented on [Mon Jul 02 2018](https://github.com/IBM/design-system-website/issues/293)

We've been getting a lot of questions asking if certain teams both in IBM and outsides can use Carbon. Need to clarify that its an open source project, need to clarify relationship with IBM Cloud and growing scope of Carbon.

**Comment by claycrenshaw** [comment]
First pass on the main message for this one. . .

Q: Who can use Carbon?

A: Anyone! Carbon is an open-source design system that is also the official product and digital design system for IBM. Carbon was originally developed to serve the IBM Cloud business unit, but has since expanded in scope to encompass all product and digital teams at IBM. Contributions are welcome from IBMers as well as the open-source community at large. @chrisconnors-ibm @jeoffw @kuehndaniel @aagonzales

**Comment by aagonzales** [comment]
Sounds perfect! #shipit

**Comment by alisonjoseph** [comment]
sounds good to me!
