### ISSUE TITLE
[Tile] Single-select tile: Consider to change the checkmark style to radio button style instead.

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-website#3611]
### Acceptance criteria

Related issue: https://github.com/carbon-design-system/carbon-design-kit/issues/729

Consider changing the checkmark style to make it consistent with the checkbox style in tiles. 

SB link: https://react.carbondesignsystem.com/?path=/story/components-tile--radio

- [x] Play this out with the radio icon to see how it would look in context.
- [x] Playback to design and a11y team.

![image](https://github.com/carbon-design-system/carbon-website/assets/77697351/3899152b-81fb-4ef7-b4a8-7cdee526ddeb)

![image](https://github.com/carbon-design-system/carbon-website/assets/77697351/70437d11-4580-4290-ba19-725bbc77b066)

**Comment by Huixh111** [comment]
i

**Comment by Kritvi-bhatia** [comment]
(Related https://github.com/carbon-design-system/carbon/issues/14722)
This issue is similar to [selectable component issue](https://github.com/carbon-design-system/carbon/issues/14722#issue-1915822286). The design solution above for tile is already been being considered.

References:
> [Tile's Audit](https://www.figma.com/file/w4QA4bnNZAiySPskA5qZMW/Selectable-Components?type=design&node-id=14-90&mode=design&t=sp9y6oFhNfdkgkpD-4)
> [Final Solution](https://www.figma.com/file/w4QA4bnNZAiySPskA5qZMW/Selectable-Components?type=design&node-id=548-4304&mode=design&t=sp9y6oFhNfdkgkpD-4) ![Image](https://github.com/carbon-design-system/carbon-website/assets/148799271/5523036a-5e7b-4081-bdc9-dc9932ae28a2)



- Further, we will be updating the final design spec in the figma kit and then document it on the [Style tab](https://carbondesignsystem.com/components/tile/style) on our website.
