### ISSUE TITLE
[Psych catalog] Playback of exploration to Cameron, Jeff, and design team

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3844]
## Acceptance criteria
- [x] Playback IA mock explorations to design team
- [x] Playback IA mock explorations to Cameron and Jeff
- [x] Have meeting with Cameron, Jeff, Scott, Aubrey, Anna, etc. to discuss the needs of having the Psych catalog on our website, and walkthrough IA mocks.
- [x] Next steps: Mock up how to the Psych catalog preferred design
- [ ] Playback and Pass to Cameron to add more introductory content around the catalog

**Comment by jeanservaas** [comment]
We decided after a design review with @mjabbink that the psychology catalog should not be added to Other Resources even as a stop gap solution without more usage documentation describing how users should apply the catalog and providing examples of it in use. We saw some great examples in the PLG onboarding patterns where designers applied the these catalog principles to help drive their layouts.

Since more content is needed to contextualize the catalog, we decided to go ahead and make the appropriate IA changes to the Carbon site to better place the catalog (rather than dumping it in Other Resources, which is a junk drawer).
Right now this issue is blocked by an IA change to the Carbon site, which we'll try to fast track: https://github.com/carbon-design-system/carbon-website/issues/3888

## Design specs for psych catalog

https://www.figma.com/file/VyoxNTCXjiojEaslOelSUC/Psych_catalog?type=design&node-id=104%3A7340&mode=design&t=4Q3Lm7yDUgIAnd31-1
