### ISSUE TITLE
[Dropdown: Combobox] Live Demo Error 

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon-website#3931]
## Acceptance criteria

The live demo under the dropdown for fluid combobox and fluid condensed combobox is showing an error.

![image](https://github.com/carbon-design-system/carbon-website/assets/158570656/d5281c52-6c43-435d-8db4-bfb90ace4072)

**Comment by riddhybansal** [comment]
Hi @Kritvi-bhatia17 this issue is not related to component in storybook, The issue is in carbon website itself. The path to the component being pulled from storybook by the carbon website is wrong. 

The address mentioned for the fluid  combobox [ experimental-unstable-fluidcombobox--default] should be replaced by experimental-fluid-components-unstable-fluidcombobox--default

Note: All fluid components should have the correct path.

**Comment by Kritvi-bhatia17** [comment]
Hello @riddhybansal, Thanks for the explanation! Do I need to edit the issue or anything? 🤔
