### ISSUE TITLE
New issue template - provide contact details (optional)

### ISSUE THREAD

**Issue by benjamin-kurien** [carbon-design-system/carbon-website#4025]
Request users to provide their contact details when creating an issue. This will help us reach out to them, prioirtise the issue, and understand the problem better. This field can be made optional.

**Comment by sstrubberg** [comment]
Just spoke with the devs about this issue. This is actually semi-intentional. By putting an email address field in the form we are implying that we will reach out to them via email which is not the case. We actually want them to continue the conversation in GitHub. 

Now, in lieu of that, we do apply [adopter labels](https://github.com/carbon-design-system/carbon/blob/17d88f6210b3f5dff28b860ec1ec1b4683caa416/.github/workflows/issue-triage-strategic-adopter.yml#L19-L29) issues so that we know the teams that have requested this. Through that, we have focals in the business that we can reach out to learn more about the given request.
