### ISSUE TITLE
Production guidelines updated for Carbon X

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#41]
Update the Carbon production guidelines for the Carbon X release.
Current: https://github.com/IBM/design-system-website/wiki/Production-guidelines

Update redlines to match updated IBM design language (duo).

**Comment by designertyler** [comment]
Also include https://github.ibm.com/carbon/issues/issues/843

**Comment by designertyler** [comment]
# Carbon production guidelines

For anyone interested in contributing to the Carbon Design System website, we follow a set of standardized guidelines to ensure consistency across the site. 

1. Read these production guidelines for best practices. 
2. Look over our [markdown cheatsheet](https://github.com/carbon-design-system/design-system-website/wiki/Markdown-cheatsheet) for how to properly style content. 
2. Create your content, images, etc. 
3. Read our [guide](https://github.com/carbon-design-system/design-system-website/wiki/Updating-content-on-carbondesignsystem.com) for how to create a PR to Carbon's `design-system-website` repo. 


# Creating content

## Images

### Sizes
<mark>To do: what are the sizes used for the Duo site</mark> We support three image sizes based on type:

| SIZE (PX)  | TYPE | 
|------- |---------|
| 290    | Half width image, small components (Ex. Buttons), and cropped images  |
| 604    | Full width image       |
| 894    | Wide format images and larger components (Ex. Data Tables)      |

The artwork in an image does not have to fill the full image size. White space is ok but the artwork should always be centered aligned on the image. If there is excessive or limited white space consider using a different size.

<mark>verify if this is still true with the new sizes</mark> **Pro-tip:** Two half width images (290px) can be arranged side by side to give the appearance of a full image. This allows images to stack a responsive breakpoints without having to generate two sets of images. 

### File type
The Carbon website supports and hosts `PNG`, `SVG` and `GIF` image formats. 

#### PNG

PNG is preferred for raster-graphics, like static images and photographs (to show redlined components, for example). 

PNG is used for graphs, diagrams, and anywhere you want to display flat colors and lines that won’t need to scale up. They are a lossless image format, which means when they are compressed, they don’t lose any data. They also allow for alpha transparency. When you need to overlay an image on a different colored background, PNG files work well. 

**Note:** Text inside of a png is not accessible and therefore a PNG should never contain important information that cannot be accessed elsewhere on the page.

#### SVG
SVG (Scalable Vector Graphic) is preferred for vector-graphics. 

Use an SVG file format when you have a flat, relatively simple asset such as logos, icons, basic shapes, and line art. Accessible text inside SVGs is possible but long strands of copy should be avoided.

#### GIF
GIFs are the preferred animation image format used on Carbon to show motion and interactions examples.
 
### Exporting PNG and SVG
For images to render properly, export them from Sketch or Illustrator by:

* Aligning all elements to the pixel grid
* Using one of the three image sizes: 290px, 604px, 894px
* Export at 2x for PNG
* Background should be transparent

### Creating GIFs
We recommend using the image sizes above and a tool called [GIF Brewery](http://gifbrewery.com/) for creating animated GIFs by recording from your desktop or open browser window. 

### Naming conventions
**Images are named using the format:** `page-name-tabname-#.png`

_Example:_

Components > Data Table > Usage tab

`data-table-usage-1.png`

`data-table-usage-2.png`


Style > Layer > Overview

`layer-overview-1.png`

`layer-overview-2.png`


### Accessibility
`Alt text` describes an image and is used for a variety of reasons. Include `alt text` so on hover the browser tooltip displays the text. In cases when an image doesn't render, the `alt text` will show in lieu of the image. Additionally, `alt text` enables users who rely on assistive technology to know what the image represents. In the HTML, make sure the `alt text` is in brackets before the image URL:

`![alt text goes here](image URL goes here)`


## Content

The website is written in markdown, which makes it easy for anyone to contribute content in a systematic way. If you are not familiar with markdown, check out Carbon's handy markdown styling [cheatsheet](https://github.com/carbon-design-system/design-system-website/wiki/Markdown-cheatsheet).

- Use sentence case except when referencing components. 
- Components are proper nouns and therefore written in Title Case. 
- Convey a friendly tone as you are writing content and avoid sounding too harsh or directive. 

_Example_: 

**Do**: 
> “We recommend validating user data before form submission.”

**Don't**: 
> “You should always validate user data before form submission.”


### Components
Each component page is divided into three tabs, Code, Usage, and Style, and differs in content given the section:

#### Code
Define the component and include any documentation for SCSS and Javascript. 

#### Usage
Explain how to use the component, which may include best practices and frequently asked questions. Use static images to support your content and GIFs when explaining interactive elements. 

If a component has multiple variations, include a comparison table to show the differences between them and when to use which variation. This table can be styled using markdown. Check out this handy [table generator](https://www.tablesgenerator.com/markdown_tables). 

**Protip**: Remember to use _quotation marks_ (“ ”) instead of _inch marks_ (" ") 

#### Style
Order applicable content by Color, Typography, Layer, then Structure. Structure may include States, Spacing, and any other component-specific variations. Add supporting images to this section, with at least one image showing how color is applied within the component and another showing structure and spacing measurements. Images are accompanied by a descriptive caption below the image and used in conjunction with the spec charts. 

**Protip**: Use lowercase when referencing HEX values (`#ffffff` instead of `#FFFFFF`).


**Spec'ing guidelines** 

<mark>Should specs be in px and rem or mini units?</mark>All style image specs are set in [IBM Plex Mono](https://github.com/IBM/type/blob/master/LICENSE.md). Numerical measurements include both pixels and rems and follow the naming convention `#px/#rem` (please note the lack of spaces between the forward slash). We recommend using this [site](http://pxtoem.com/) for converting pixels to rems. The increment unit `##px/##rem` only needs to for one measurement per image; the remaining measurements can simply read `##/##`. Measurements are presented horizontally for readability and never flipped vertically to fit smaller spaces. Specs can be broken up into two lines if necessary.

Keep as many spec lines and measurements outside the component as possible for easy readability. 

<mark>Needs updating</mark> 

| PROPERTY                | SPACING (PX) | 
|-------------------------|--------------|
| Spec line & component   | 6            |
| Measurement & spec line | 4            |

![spec-example-1](https://media.github.ibm.com/user/10073/files/c6e9fbdc-af60-11e7-9e67-71a41332c2b9)

Spec lines have a 1px thickness and flat ends. To add endings to an open path in Sketch, go to the Borders section in the right-side panel, click the gear icon and select the flat end option for both the start and end arrow dropdown menus. 

![Adding flat ends to a line in Sketch](https://media.github.ibm.com/user/525/files/de3259b6-af50-11e7-9a27-9a2499595a9c)


**Spec'ing color usage**<mark>Needs updating</mark> 

| ITEM              | COLOR   | PURPOSE |  PX/REM | 
|-------------------|---------|---------|---------|
| Pink lines        | #ff00ff | Height and width measurements for a component as well as key elements within a component such as row height | - |
| Pink text         | #ff00ff | - | 10/0.625 |
| Green blocks  | #00ff80 @ 40% opacity | Internal edge padding/margin, and internal spacing between component elements |  - |
| Green text & lines| #007d7d | - | 10/0.625 |
| Blue blocks   | #00ffff @ 40% opacity| External padding/margin, and can also be used internally if there are too many overlapping green blocks |  - |
| Blue text & lines | #007d7d |  - |10/0.625 |


### Annotation
**Purpose**

To call attention to and annotate specific areas.

| **Item** | **Style** |
|:-------------------|:-------------------|
|Annotation Number|14pt IBM Plex Mono|
|Purple Field|Purple 20 #e6d6ff|
|Magenta Field|Magenta 40 #fa75a6|
|Cyan Field|Cyan 50 #1193e8|

![annotation_overview](https://user-images.githubusercontent.com/19270502/45712563-468a9600-bb52-11e8-92f4-10cd1e006b51.png)
![annotation_2](https://user-images.githubusercontent.com/19270502/45712565-4ab6b380-bb52-11e8-9fc8-51c0cb09b26c.png)


### Annotation - Alternate
**Purpose**

To call attention to and annotate specific areas.

| **Item** | **Style** |
|:-------------------|:-------------------|
|Annotation Number|14pt IBM Plex Mono|
|Dash Line|1px thickness with 3px dash and 1px gap|
|Cyan Field|Cyan 50 #1193e8|


![annotation_overview_1](https://user-images.githubusercontent.com/19270502/45712601-5e621a00-bb52-11e8-93ab-69b31c035ca8.png)
![annotation](https://user-images.githubusercontent.com/19270502/45712606-615d0a80-bb52-11e8-9042-ac972abf67ee.png)


### Measure
**Purpose**

To mark the fixed size of an element and the space between elements.

| **Item** | **Style** |
|:-------------------|:-------------------|
|Measure label|14pt IBM Plex Mono|
|Size Measure|Magenta 40 #fa75a6|
|Space Measure|Magenta 60 #8a3ffc|

![label_overview](https://user-images.githubusercontent.com/19270502/45712627-6e79f980-bb52-11e8-96e2-c0780f30ad18.png)
![measure](https://user-images.githubusercontent.com/19270502/45712635-733ead80-bb52-11e8-9d05-444f15792350.png)


### Spacers
**Purpose**

to determine the spacing that surrounds any Duo component.

| **Item** | **Style** |
|:-------------------|:-------------------|
|Measure label|14pt IBM Plex Mono|
|Size Measure|Magenta 40 #fa75a6|
|Space Measure|Magenta 60 #8a3ffc|

![spacers_overview](https://user-images.githubusercontent.com/19270502/45712652-7c2f7f00-bb52-11e8-9e39-7bce97353d91.png)
![measure_spacers](https://user-images.githubusercontent.com/19270502/45712663-82256000-bb52-11e8-801f-dd5d3698d414.png)


### Boundaries, Alignment, & UI truncation
**Purpose**

To show alignment, padding, and boundaries of an element.

| **Item** | **Style** |
|:-------------------|:-------------------|
|Purple Padding|Purple 20 #e6d6ff, Blending: Multiply|
|Purple Boundaries|Purple 40 #bb8eff, 1px thickness with 3px dash and 1px gap|
|Magenta alignment| Magenta 60 #d12765, 1px thickness|

![padding_boundaries_alignment_overview](https://user-images.githubusercontent.com/19270502/45712681-8fdae580-bb52-11e8-8b9d-d1c19479983e.png)
![padding_boundaries_alignment](https://user-images.githubusercontent.com/19270502/45712689-923d3f80-bb52-11e8-8484-269448ef46b9.png)


### UI Truncation
**Purpose**

To imply there is more to the UI when it is not practical to show the whole UI element.


| **Item** | **Style** |
|:------------------|:---------|
| Zig Zag Line |Gray 30 #bebebe |

![truncation_overview](https://user-images.githubusercontent.com/19270502/45712693-98332080-bb52-11e8-882e-c058c14c9fac.png)
![ui_truncation](https://user-images.githubusercontent.com/19270502/45712697-99fce400-bb52-11e8-898f-6b3f893f1a34.png)


### Do's & Don'ts
**Purpose**

To show examples for correct and incorrect ways to implement a UI element.
![do_dont](https://user-images.githubusercontent.com/19270502/45712706-9ec19800-bb52-11e8-9489-75d0e7d3cf90.png)

**Comment by jeanservaas** [comment]
Looking much better! Just some thoughts and I'll attach some sketchbook style grabs of my explorations with Chiu's style.

One thing I think we need to be clearer on (and I'm running into this looking at the guidelines too... is when we use the measure treatment and when we use the spacers... They're going to be used together a lot too so maybe some kind of logic to drive that would be good. 

Also the checkerboard treatment gets to be a little much and I think we should be sparing with it's use and maybe only reserve it for minimal moments in guidance. Maybe we only checkerboard if it's a 8px mini unit and all other distances get measures (not sure, just an example...) I've been playing with that too in my stuff.

Also 2, I still think we're a little too dark with the annotation areas. 

### Checkerboard (mixing measures with spacers)


![screen shot 2018-09-18 at 3 18 27 pm](https://user-images.githubusercontent.com/43144260/45714598-bbac9a00-bb57-11e8-8cdc-3ced55f6c6b9.png)

### Checkerboard to articulate larger sizes

![screen shot 2018-09-18 at 3 54 26 pm](https://user-images.githubusercontent.com/43144260/45715995-3dea8d80-bb5b-11e8-9a74-0832b704798b.png)


### Spacers (Can we mix box / spacer use in guidance?)

![screen shot 2018-09-18 at 3 50 12 pm](https://user-images.githubusercontent.com/43144260/45715894-ecda9980-bb5a-11e8-8ca8-f91b32a6b049.png)
 

### Annotation style (not figured out, quick color sketches)


![screen shot 2018-09-18 at 3 39 38 pm](https://user-images.githubusercontent.com/43144260/45715198-3a560700-bb59-11e8-8e41-2bfd926832db.png)

![screen shot 2018-09-18 at 3 43 24 pm](https://user-images.githubusercontent.com/43144260/45715315-9a4cad80-bb59-11e8-99f5-5982a84c472e.png)

 
![screen shot 2018-09-18 at 3 46 18 pm](https://user-images.githubusercontent.com/43144260/45715527-147d3200-bb5a-11e8-9271-6c5c68214018.png)
![screen shot 2018-09-18 at 3 20 50 pm](https://user-images.githubusercontent.com/43144260/45715564-25c63e80-bb5a-11e8-9c6d-1963450781de.png)

**Comment by laurenmrice** [comment]
## Redlines for components 

![Artboard Copy 2.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/83c1cea2-3045-43a6-8344-903e2078aa86)

**Comment by laurenmrice** [comment]
Style tabs for all components: images and redlines

- [ ] Accordion
- [ ] Breadcrumb

**Comment by laurenmrice** [comment]
Style tab: images and redlines

https://ibm.ent.box.com/file/365293158182

**Comment by alisonjoseph** [comment]
the new styles look so nice! 🙌

**Comment by aagonzales** [comment]
Close when images are done and content has been update on the production guidelines [wiki](https://github.com/carbon-design-system/carbon-website/wiki/Production-guidelines)
