### ISSUE TITLE
Update typography guidelines page with new type tokens (styles)

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#414]
Update core typography or create new experimental typography tab for new tokens depending on implementation.

**Comment by jeanservaas** [comment]
# Type Elements v10

**Sketch File**
https://ibm.box.com/s/twn7uc9vsfexk4tocs1m03qi9w5a9q21

@aagonzales @eraymond25 

Here's how I handled the new type pages for Carbon (the tokens are in there too). Structure should be similar to what Anna and I outlined last week:

1. Unlike the digital site, we stayed away from the higher-level typographic guidance, pulling in only the UI type specs content from the DL site that applies to both Editorial and Product themes; **(**Biggest change:** I moved "Fluid type" and "Line Length" into their respective sections so they can be with their type sets. There's no way the "Line Length" dropdown can accommodate all of the type tokens... so if we don't like this, we should think about simplifying this guidance like the digital site has done.)**

2. I pulled apart Product and Editorial themes into different tabs... I borrowed from both the opening content of Carbon and the opening content of the digital site for the intro copy... It needs some help, but it's a start.

3. The type sets within both Product and Editorial have component tokens and layout tokens... so I modified the design to make more of a sub-tab module within the page. I tried some other designs / content switchers, but this one worked the best.

4. You'll see that the Editorial page Layout tokens are the only ones that have the breakpoint slider.

[Elements_v10.pdf](https://github.com/carbon-design-system/carbon-website/files/2617564/Elements_v10.pdf)

**Comment by aagonzales** [comment]
**Feedback:**
- Other than refining some of the content I think it looks good!
- Not sure you need the getting started section ... or at least not the Kit download. Seems redundant and the type stuff is scattered across the carbon and IDL files.
- These last two examples are actually confusing, might help to put them in context. Otherwise they just looks like the bad examples a couple of rows up.
<img width="338" alt="image" src="https://user-images.githubusercontent.com/11670886/49098384-beed9180-f23c-11e8-9c3e-a78f6ef1a8d1.png">
- Under Production theme -- "v19a" is related to editorial/digital only. We'll need to work on that sentence some to get the correct context.
- I think for editorial you might want to lead with Layout tokens instead of components, seems like those would be primarily used

**Comment by eraymond25** [comment]
Looking really good, a few things:

1. Are we married to this style anchor link? I see it happening in the Design Language site and it looks a bit out of place and chunky to me. I get what they are doing, but maybe we could do it in a bit more graceful way.

![screen shot 2018-11-27 at 2 05 08 pm](https://user-images.githubusercontent.com/12436158/49108337-9326d780-f24d-11e8-9aa4-17ec37da561a.png)

2. The term editorial is used all over here and I've always found it confusing that we have Digital Design but it uses the Editorial typescale. Nowhere on this page says digital or ibm.com so I'm not immediately aware of what Editorial actually means. We have been talking about naming structures a lot lately since we're now using the IBM Design System as a code base... does Digital Design still make sense? Does editorial type make sense? Why are they not in coordination with each other?

3. Why did we switch from heading to header? It doesn't feel right saying header

4. The tokens may need to be class names for us @photodow can you weigh in on this? Are we able to use tokens or no?

This answer will mean we need to change the content under "IBM Editorial theme (look at content)"

5. I think layout tokens tab should come first and component tokens should come second in both pages since thats mainly what people will be learning since the components are already made.

I also think in this tab we can be specific and say "Product layout tokens" and "Editorial layout tokens"to better exaggerate the fact that these are two different sets
![screen shot 2018-11-27 at 2 11 59 pm](https://user-images.githubusercontent.com/12436158/49108731-8eaeee80-f24e-11e8-91c9-899dc2ecaa3a.png)


6. These should both be sticky, the way you have it with the breakpoint tabs indented might look odd when it's sticky

![screen shot 2018-11-27 at 2 15 43 pm](https://user-images.githubusercontent.com/12436158/49108945-0a10a000-f24f-11e8-9a84-c0baa13f4e51.png)

7. Agreed with Anna, the Design kit tile should be actually just pointing to the design kit page rather than a download link. I also would take .sketch out because we're going to be adding other file types in there and actually currently have other file types in there today.

8. You have the word Carbon under Typeface: IBM Plex :) need to take that out

**Comment by aagonzales** [comment]
Closing and tracking final designs here: https://github.com/carbon-design-system/carbon-website/issues/475
