### ISSUE TITLE
[UI Content Design Guild] Data table component topic is missing content 

### ISSUE THREAD

**Issue by lesnider** [carbon-design-system/carbon-website#4235]
https://carbondesignsystem.com/components/data-table/usage/

Need explicit guidance for creating content for data tables.

**Comment by laurenmrice** [comment]
## Issue refinement
- I went through the attached document above. I made some comments in it here:
  - [Data_table-UIContentGuild-comments+edits_LR comments.docx](https://github.com/user-attachments/files/17017499/Data_table-UIContentGuild-comments%2Bedits_LR.comments.docx)
- Most changes mentioned in the document are doable as part of this issue and I would size it as an 8. However there were a couple things that would need to be addressed in separate issues, which I will list below.

---

### Separate issues
Separate issues would need to be created to tackle the following: 

**1. Live demo changes** 
> - PB: The Dropdowns in Variant Selector do not all contain explanations,  indicating differences. Batch Actions has lorem ipsum text.
> - List items should be in sentence-style capitalization

These above points would need to be listed in separate issue created in the [carbon repo](https://github.com/carbon-design-system/carbon/issues/new?assignees=&labels=type%3A+enhancement+%F0%9F%92%A1&projects=&template=FEATURE_REQUEST_OR_ENHANCEMENT.yaml&title=%5BFeature+Request%5D%3A+) for dev. This needs to first be resolved in the storybook, and then it will be fixed in the live demos on the website.

**2. Accessibility testing status changes**
> - We're wondering if it's important to have this Accessibility section on every Usage tab, when there is an Accessibility tab
> - Also, per the anchor link section at the top, Accessibility testing status is a subsection of Live demo, which doesn't make sense. Either make it a top level section or remove it

This hierarchical change of where this section appears on the Usage tab would need to put in a separate issue in the [carbon-website repo](https://github.com/carbon-design-system/carbon-website/issues/new?assignees=&labels=type%3A+bug+%F0%9F%90%9B&projects=&template=docs-issue.yaml&title=%5BDocs%5D%3A+) because the outcome of this decision will affect all Usage tabs for components. And yes, this section needs to be on every Usage tab. In the issue, it would be good to suggest alternative solutions of where to place this information and make sure it would scale well across all components.

**Comment by crlordan** [comment]
[The document](https://github.com/user-attachments/files/17017499/Data_table-UIContentGuild-comments%2Bedits_LR.comments.docx) lists that the gutter modes link is broken. This was something we found during our initial investigation. I fixed the link in this PR: https://github.com/carbon-design-system/carbon-website/pull/4194

**Comment by crlordan** [comment]
PR #4312 has these changes:

- Copy edits for the Universal Behaviors section.
- Added a subhead to the entry in the Modifiers section, to match other components and label the modified more clearly.
