### ISSUE TITLE
[Pages] Guidelines: Content

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#479]
- [ ] Tab: General
 Need to replace images with new image assets
![image](https://user-images.githubusercontent.com/15144993/49240409-b32fd580-f3ca-11e8-8a67-61129de3acf4.png)

- [ ] Tab: Guidance
 Need to replace images with new image assets
![image](https://user-images.githubusercontent.com/15144993/49240421-baef7a00-f3ca-11e8-90ff-428a1ab4d672.png)

- [ ] Tab: Glossary
Dos and Donts. Not anything new here. Should be all covered in other issues.

**Comment by claycrenshaw** [comment]
Content updates for this section are not in scope for the Carbon X release. This is backlog work.

**Comment by shixiedesign** [comment]
Group decision: lets just remove them for this release.

**Comment by laurenmrice** [comment]
I did make headway on these designs. 

File: https://ibm.ent.box.com/file/359636513915

Screenshots
## General
![content_general](https://user-images.githubusercontent.com/43969356/49300507-074cbf80-f488-11e8-8b88-efe1f0f4893a.png)

## Guidance
![content_guidance](https://user-images.githubusercontent.com/43969356/49300524-0d42a080-f488-11e8-912a-7f54493a538f.png)

## Glossary (cropped view because its very long)
![content_glossary](https://user-images.githubusercontent.com/43969356/49304512-2ea88a00-f492-11e8-9fba-6381134421a7.png)
