### ISSUE TITLE
[UI Shell components]: remove codepen frame

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#496]
Users are getting confused by the code pen frame on top of our shell components. Can we remove/hide this?

![image](https://user-images.githubusercontent.com/11670886/66957444-dfc4fe00-f02b-11e9-9fb5-ee28e9ee3cc9.png)

**Comment by alisonjoseph** [comment]
I think this was added so we could get the code examples into the website, because we're using the shell on the site w/ overrides the overrides were being applied to the shell example also and it was displaying incorrectly. 

Do we want to just remove the examples entirely on this page and link out to the Storybook for now? Or leave it until we have time to get normal in page examples working?

**Comment by aagonzales** [comment]
We can just leave it for now, but should be fixed it at some point. If we think the new component display window Vince is working on will resolve this than we can close this issue.
