### ISSUE TITLE
Dialog pattern

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#549]
**Abstract**
Guidance and best practices for how to appropriately use dialogs (modal dialog and modeless dialog)

**Link to preview**
Boxnote (WIP): https://ibm.box.com/s/2v299xeyh63lee4tiaevzsai81sq84lk
Preview link: https://carbon-website-git-fork-aagonzales-dialog-pattern.carbon-design-system.now.sh/patterns/dialog-pattern

**Next steps**
- [x] Pattern audit
- [x] First draft
- [x] Peter Vachon 12/10/19
- [x] Luke Firth 12/10/19
- [x] Alex Swain 12/12/09
- [ ] Chris Connors' review
- [ ] Image review (Jeannie)
- [x] Content review (Jan) 12/12/19

**Comment by aagonzales** [comment]
From @connor-leech (moved out of intro comment) 

## Existing modal guidance

* [Carbon](https://www.carbondesignsystem.com/components/modal/usage)
* [Cloud PAL design jam](https://ibm.ent.box.com/folder/76577445842)
* [Cloud PAL notification](https://pages.github.ibm.com/ibmcloud/pal/experimental/notification-usage/) (Note: This guidance is focused on notifications and would likely be more fitting within our notification guidance. I'm including it here because we suggested it go under modal guidance on the spreadsheet.)
* [WCE](http://billboard1.fyre.ibm.com/component-library/messages-nag/design)

**Comment by janchild** [comment]
This pattern has been published.
