### ISSUE TITLE
Update link on Get Started - Design tab to new idl v2 library

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#577]
Need to link IDL v2 library to this card on step 3. People are getting confused as to why they are using an outdated library (v1).

![Screen Shot 2019-11-11 at 3.52.34 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/28155987-346f-4d54-9252-e9583ac07325)

Ref: https://github.com/carbon-design-system/carbon-design-kit/issues/227

**Comment by josh-tt** [comment]
Thanks Lauren, sorry to beat a dead horse, but if I'm understanding correctly, the latest Carbon themes **still** reference the V1 library file in certain places and therein lies the confusion/complication. 

Below is one example of many v1 library references I found in the latest Carbon theme (that is not a hover, but simply an older color). As you can see in this example, the v1 shared style is being used in the latest Carbon theme. Replacing that means knowing the color value (or shared style name) for the v1 in order to find/replace it or target it via code using a scss > sketch plugin. 

**Example of 'non-hover' colors from v1 doc being used in latest Carbon doc:**
https://snipboard.io/0UdL8X.jpg
https://snipboard.io/Rplo7C.jpg

If these are something you're not aware of, let me know if I can help you by making a list of all the instances of v1 colors from the v1 Language document being referenced in the latest Carbon themes.

My current plan, until this is addressed is to simply override the v1 color library doc with v2 colors and keep the v1 doc on my system as a shared library. (The link to the v1 doc is needed for this). This way when the Carbon theme is pointing to the styles from v1 library, it's at least using the proper v2 colors (with the exception of hovers, which will still look to the v1 document colors until there is a v2 solution).

**Comment by laurenmrice** [comment]
Thanks for bringing that up around Tags and Low contrast notifications, if you are seeing other instances it would be helpful to let use know! We currently are revising the way we treat our color hover states (example: on filterable tag close icon) and will possibly be going with a dark/lighten approach, this won't be implemented till v11. Low contrast notifications we will switch over.

**Comment by josh-tt** [comment]
@laurenmrice

Sure, I'd be happy to help, however after checking, there are **lots** of instances of wrong/old styles in the doc.  Rather than doubling up work (I'd fix them for you if I could), I'd suggest you review the style inventory doc I've made for you first, and then consider the approach for fixing it outlined below.. 

**1. Style Inventory** 
I've created a Spreadsheet with all the theme styles found in the library files and which libraries they reference.  You will notice lots of references to old v1 library, the icon libraries and other themes. It's hard for me to tell which are mistakes and which are intentional, but I suspect many are mistakes.

**Numbers format Style Inventory (original):**
https://drive.google.com/file/d/1ymmsD21N90G6PRw22RdcuFbGYGV7tZMf/view?usp=sharing

**Google Sheet format (auto converted from numbers, so formatted a bit ugly):**
https://drive.google.com/file/d/1z2_M3YpmxfGFhxCWXox7XqDOwK2wH2lt/view?usp=sharing

(If you want to do this yourself from scratch, it takes about 3 minutes to inventory each theme once you know the process and if you use Runner and don't run into any spreadsheet issues pasting the data, which can be quickly fixed in VScode). 

**Instructions to create a style inventory that includes external libraries:**
https://drive.google.com/file/d/1ytq2vO42n-kszAr8DE6G2jXT2jOUcP82/view?usp=sharing

NOTE: One thing you may notice is there are lots of duplicates, like color/black, with the same shared style name. This is not a mistake in my document, but I believe this is from referencing a library that had the same style name, but a different object id or something like that and got left behind in your theme file.  In any case, it's some 'style junk' left over in there it seems. It's not a big issue, as you will be able to replace that style later if needed. 

**2. Go through the spreadsheet and add the correct new styles to it in a new column.**

**3. Next, replace incorrect styles with new styles in the Carbon themes:**

Use the Automate plugin to batch find/replace layer styles (and text styles) to do so.  

*If you prefer to use a more manual method to correct the items one by one (if you don't trust the plugin to do it for you or it's running too slow), you can use the Shared Styles Finder plugin which will take to you to each symbol instance that uses any given style and then you can manually re-assign it the correct color using overrides drop down. 

You can just do this right away without making an inventory spreadsheet of course, but I think having a list outside of Sketch is smarter approach first and keep track of the changes, as it's easy to get lost in Sketch. It would also be a nice way to provide users with info about color assignments as well. 

**Lastly, a suggestion:** 
I'd personally rather have the themes point to the color library file for colors so that colors are separate from the theme itself, which is more future proof and easy to manage. You could have a single Color doc with pages for v1, v2, ... v3 swatches and theme tokens pages that use the colors. The theme would then reference the master Color library and be future proof for new versions as well. The only downside is that the user would have to have both sketch files installed and would have to make color changes from the Color Library document, but it would be much easier to manage. It's possible I'm just not understanding some of the requirements, but I wish it worked that way. 

Let me know if I can help or if you need some more info.
