### ISSUE TITLE
Support one-click sketch Add Library capability

### ISSUE THREAD

**Issue by jeoffw** [carbon-design-system/carbon-website#580]
Use the install button url protocol handler as demonstrated on sketch web site:
https://sketchapp.com/libraries/

Example:
```
sketch://add-library?url=...
```

Doc on shared libraries:
https://sketchapp.com/docs/libraries/shared-libraries

**Comment by aagonzales** [comment]
- [ ] make Sketch library account with carbon email
- [ ] design what it will look like on the website

**Comment by shixiedesign** [comment]
Re-worked the Getting Started designer page content to include the 1-click library install Jeoff asked. Almost all of the current content is still here. I gave some an H2 and anchor links since they are pushed further down the page. Change suggestions welcomed!

![designer](https://user-images.githubusercontent.com/15144993/52390614-fc517500-2a5e-11e9-83bf-45384f62874e.png)
