### ISSUE TITLE
Notification pattern dev review

### ISSUE THREAD

**Issue by jillianhowarth** [carbon-design-system/carbon-website#628]
Notification pattern draft: https://www.notion.so/carboncontent/Notification-Pattern-1d660b5de7a24795afd3d9c9b248f280

I'm looking to make sure all this makes sense and works from an implementation perspective.

**Comment by joshblack** [comment]
Looking great! Wanted to leave some feedback inline here, let me know if there is a better way to leave feedback on Notion or anything else that you're using 😄 

### Accessibility section feedback

Would be great if we could link out to WCAG 2.1 instead of 2.0. I think the relevant links would be:

https://www.w3.org/WAI/WCAG21/Understanding/interruptions.html

https://www.w3.org/WAI/WCAG21/Understanding/no-timing.html

One thing that may have changed in this new guidance would be 2.2.3:

> The intent of this Success Criterion is to minimize the occurrence of content that requires timed interaction. This enables people with blindness, low vision, cognitive limitations, or motor impairments to interact with content.

This could conflict with the best practice under Toast > Best practices which specifies a time limit:

> Toasts dismiss after 5 seconds.

Definitely not 100% certain though, and ultimately could be a user preference at the end of the day similar to 2.2.4.

#### Screen readers and live regions

One detail that could be helpful to call out is that we create live regions through a combination of `aria-live` and `role="status"`. Live regions are helpful because they announce their content without a user explicitly interacting with that area on the page.

One thing that could come up is around what happens if multiple notifications, and subsequently live regions, are now on the page. Without any extra work, the user would hear each live region announced in the order it was added to the page. There may be something valuable here to share about adding delay between when these are shared with the user in order to provide a better experience.

#### Reaching a notification

Loved that you called out not moving focus and keyboard operability, one thing I'm curious about is how this ties into the timing of dismissing notification automatically.

In order to reach the notification, a screen reader or keyboard user might need to figure out where on the page it is in order to navigate to it. Something that may come up is that the time it takes them to navigate to the notification may be longer than the automatic dismissal window and may be frustrating.

### Patterns

#### Modal

One thing that might be helpful to talk about for Modals would be the requirement around trapping focus within the modal.

Reference: https://www.w3.org/TR/wai-aria-practices/#dialog_modal


### Questions

- Was curious how would notifications work alongside screen magnification tools when viewing stuff at 400%
- How many notifications are allowed on the screen at one time? What order should they appear in, especially if they have different priority levels
- What happens if multiple live regions are created, like for communicating loading state or some other region behavior, alongside a notification? How should things be announced?
- When would someone choose a UI-level notification instead of sending a notification through the OS's notification system? Was curious when would someone prefer one's in the UI versus push notifications that we can send from the browser

**Comment by dakahn** [comment]
I mirror the points that @joshblack brought up; @snidersd tagging you in this thread so that maybe we could get some clarity around a few of these questions.

- If an input throws a notification (toast), but the user is magnified 400% how would that user expect to see that alert since it'd be out of the zoom viewport?
- How has IBMa handled multiple announcing live regions in the past? I would think it could quickly get cacophonous. Should the `assertive` alerts stomp over non assertive ones?
- Also wondering if there's any existing guidance along these lines we could draw from. Thinking about composing components into accessible patterns.

**Comment by snidersd** [comment]
@dakahn 
- If an input throws a notification (toast), but the user is magnified 400% how would that user expect to see that alert since it'd be out of the zoom viewport? 
**Investigating...**

- How has IBMa handled multiple announcing live regions in the past? I would think it could quickly get cacophonous. Should the assertive alerts stomp over non assertive ones?
**Short answer is "Yes" aria-live="assertive" take priority. 
Here is a link to WC3 ARIA Authoring practices that explains the [aria-live regions usage.](https://www.w3.org/TR/wai-aria-1.1/#aria-live)** 

- Also wondering if there's any existing guidance along these lines we could draw from. Thinking about composing components into accessible patterns.
**The latest ARIA Authoring Practices includes [Alert and Message Dialogs](https://www.w3.org/TR/wai-aria-practices-1.1/#alertdialog ).**

**Comment by snidersd** [comment]
@dakahn The following information listed below is in regard to the question: "If an input throws a notification (toast), but the user is magnified 400% how would that user expect to see that alert since it'd be out of the zoom viewport?" 
- It is a design decision on how to handle a notification when it is magnified, but it would not fail any WCAG requirement by not putting a toast notification into the viewport (unless it is modal).
- WCAG 1.4.10 Reflow isn't about magnification. The main requirement of Reflow is that text that is transformed fits on a screen without horizontal scrolling.
- In most implementations, the user is unaware of the toast notification if they aren't viewing the region of the screen where the toaster appears.
- One possible design decision is to elect to have some kind of small affordance that allows the user to display the toaster message if they desire.
- What the team does need to consider is possibly the designation of a toaster message as a status message if it is the result of a user action. See WCAG 4.1.3.
- How a team elects to handle toaster-like messages in the mobile browser version of an app is exactly how they would handle it on the desktop zoomed to 400%.
