### ISSUE TITLE
Overflow menu is not opening on IE11

### ISSUE THREAD

**Issue by reinisg** [carbon-design-system/carbon-website#630]
## Detailed description

Environment: Win10, browser IE 11.476
I went to Overflow menu section in Components demo code and tried to open that menu, hover worked fine (some styling issues), but when I clicked - nothing happened. Is it possible to resolve this issue?

## Steps to reproduce the issue

1. Open https://www.carbondesignsystem.com/components/overflow-menu/code/ in IE11
2. Click on one of the overflow menu icon

## Screen recorder

- https://files.fm/f/ty6bbttz (sorry about upload quality, it is little blurry, if need better quality I can upload)

**Comment by jnm2377** [comment]
@vpicone should we move this to the `/carbon` repo the website is just consuming the components for component demo? this would be an actual bug in our component, right?

**Comment by vpicone** [comment]
@jnm2377 @reinisg while Carbon makes every attempt to accomodate ie11, the website does not. We intentionally don't polyfill/prefix for ie11 because it bloats the bundle and makes up so little of our traffic. (it literally shows up as 0% in our tracker) ![Screen Shot 2020-01-16 at 11.12.39 PM.png](https://images.zenhubusercontent.com/5deea65833c75ca22dbfaca3/b8b08bb5-b913-45d0-97a5-ec0ca683ca91)

For that reason, you shouldn't use the Carbon website as a gold standard for ie11 compatibility of Carbon components. I'd use these framework-specific documentation site for that:

[React](https://carbon-components-react.netlify.com), [Vanilla](https://the-carbon-components.netlify.com)
