### ISSUE TITLE
[Type package in Mobile]: The serif is not the latest version in mobile for some reason?

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#781]
@joshblack In this image the serif is heavier than the Sans and the new version I made it a bit light er to balance better with the sans. In Desktop it totally looks correct. Not sure that can even happen but it’s definitky the old version. in mobile. Could it be I need to clear cache?

![img_2277](https://user-images.githubusercontent.com/32881239/51687785-421f2f80-1fc1-11e9-8be8-d542eb00520f.jpg)

**Comment by mjabbink** [comment]
left is mobile. You can see the Serif is a hair heavier indicating it’s the old version.


<img width="1222" alt="screen shot 2019-01-24 at 10 23 12 am" src="https://user-images.githubusercontent.com/32881239/51688216-210b0e80-1fc2-11e9-9532-0295dee10c3d.png">

**Comment by mjabbink** [comment]
Also, the size should be next size down so  "IBM Plex Mono" stays on one line.

**Comment by joshblack** [comment]
Hey @mjabbink! Is the new version up on Google Fonts already? Let me know and I can try updating the type package with the new resources from them to see if it helps. In the future, might be better for all of our design sites to use the same CDN for fonts so that we can control the version of fonts we're using a little better.

cc @alisonjoseph for the font-size bit
