### ISSUE TITLE
[body copy] Do not need to start Sentence with semibold word.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#820]
@claycrenshaw @jeanservaas 
No need for this initial word in semibold. I’d prefer if you try the entire paragraph (for the ones at the top of page) to be a larger size so it clearly feels like intro copy for the whole page.

For the paragraphs down the page just start sentences with regular weight and not semibold.

<img width="547" alt="screen shot 2019-01-29 at 12 17 56 am" src="https://user-images.githubusercontent.com/32881239/51885899-8dd42f00-235b-11e9-9efd-d54fde44f613.png">
<img width="676" alt="screen shot 2019-01-29 at 12 17 01 am" src="https://user-images.githubusercontent.com/32881239/51885900-8dd42f00-235b-11e9-99c1-b7b9b1daeebc.png">
<img width="712" alt="screen shot 2019-01-29 at 12 16 51 am" src="https://user-images.githubusercontent.com/32881239/51885901-8dd42f00-235b-11e9-8f90-92f4804070ef.png">

**Comment by claycrenshaw** [comment]
@mjabbink We have been moving to using italics instead of bold for the initial mention of a "system term" for lack of a better word at the moment. I agree that the bold is too much. But we really do need something to clarify those terms in context, and using quotation marks isn't quite right either. In the example above, if we just said "Cancel stops the current action. . ." the sentence gets harder to read... "What are "cancel stops?!" Are you cool with using italics for these cases?

**Comment by claycrenshaw** [comment]
Just to clarify, I'm not talking about starting all sentences with italics, but just using them to denote those "system terms" when needed for clarification.
