### ISSUE TITLE
IE11: Code snippet minimum height makes horizontal scroll bar overflow

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#975]
![image](https://user-images.githubusercontent.com/1691245/52496105-19d62a00-2b98-11e9-96eb-9f3e82fdba32.png)

Windows is going to show scroll bars. But if you look at the focus state in MacOS Chrome you can the textarea is larger than it needs to be.

![image](https://user-images.githubusercontent.com/1691245/52496153-3a9e7f80-2b98-11e9-9766-cc48b126ebd8.png)

This can be cleaned up to look better in IE11.

**Comment by jnm2377** [comment]
> Windows is going to show scroll bars. But if you look at the focus state in MacOS Chrome you can the textarea is larger than it needs to be.

@mattrosno The text area is larger so that the scrollbar would be below the code snippet container (as per the design specs for it). Would adding something like `outline: none;` for its focus style fix that? The text isn't focusable in Chrome or Safari so users can't really see that it's taller than the container.

**Comment by mattrosno** [comment]
@jnm2377 per that first screenshot, it's not consistent between `code-example` and `bx--snippet`. Since scrollbar sizes are different per OS and browser, I'd keep it simple and not have the focusable snippet container overflow outside of the snippet element.
