### ISSUE TITLE
Restructure Code tabs so all content is not living in a <component-docs> component

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#988]
Could we figure out a way to rework these code pages so that edits can be made directly in markdown like all the other pages?

**Comment by jnm2377** [comment]
The documentation is pulling from the readme.md for each component in the Carbon-components repo. I was just saying yesterday that we’ll need to submit PRs for any doc changes there. They make be included in that repo so that contributors can find immediate documentation there, but I’m not 100% sure, that was just my assumption. If designers will be doing a lot of markup change for that in the future, I’m sure it would be helpful to have it live in the website repo instead.

**Comment by alisonjoseph** [comment]
These docs need to live in the component repos for anyone consuming the library. Moving them to the website repo would mean maintaining two sets of docs, which wouldn't be idea..
