### ISSUE TITLE
"Decision tree" section in layout feels unfinished

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#996]
The "decision tree" section in layout feels unfinished or the visual could tie to the text a little better.

https://next.carbondesignsystem.com/guidelines/layout#decision-tree

<img width="837" alt="screen shot 2019-02-08 at 12 44 59 pm" src="https://user-images.githubusercontent.com/19270502/52498846-80127b00-2b9f-11e9-9f80-36a7ce87a5f6.png">

**Comment by designertyler** [comment]
Tagging @jeanservaas and @claycrenshaw  I found this section during our QA and the text and image seemed disconnected and vague. Could we add clarity to the guidance and image?

**Comment by jeanservaas** [comment]
@designertyler we need to prioritize where we need guidance clarity (there are a lot of places right now admittedly). Since we don't have bottomless content resources and Layout was the section thus far that's had the most attention... I'm not sure this is high in the pipeline right now. After the discussion with Mike and the team yesterday, I think we should focus on really fleshing out the guidance in the Typography elements section ... also the "Getting started" user flow. 

I would close this for the moment.

**Comment by claycrenshaw** [comment]
@jeanservaas @designertyler Instead of closing issues that are low priority, shouldn't we just backlog them so they don't disappear down the road?
