### ISSUE TITLE
Filtering  Dropdowns/MultiSelect & Tables for React components

### ISSUE THREAD

**Issue by OmarSherif96** [carbon-design-system/carbon-website#997]
Hello,
How can I add a filter option to these components ? I read the docs and checked github issues but I can't find it.

I tried embedding the Search component as well in the Dropdown but it doesn't work.

Can someone please provide a working example of how to filter lists/tables ? 

Thanks

**Comment by jnm2377** [comment]
Hi, you can view an example of our filterable multiselect here: https://www.carbondesignsystem.com/components/dropdown/code#filterable-multiselect
You simply have to use `<MultiSelect.Filterable/>` rather than just `MultiSelect`. 

As for the data table, there's a prop that is used to filter rows, although it has a default filter already. If you wanna customize the filtering, though, you can do that with the `filterRows` prop.

![Screen Shot 2020-03-10 at 2.39.56 PM.png](https://images.zenhubusercontent.com/5be9d7ed0cefa317ea423a50/2e6d2f69-a167-4ab4-8b43-af1662f58d10)

You can view the working example here: https://react.carbondesignsystem.com/?path=/story/datatable--with-batch-actions Whatever you type into the search bar will be filtered. 

![Screen Shot 2020-03-10 at 2.42.20 PM.png](https://images.zenhubusercontent.com/5be9d7ed0cefa317ea423a50/da858d72-cb5a-474a-ae43-c91b038b054b)

Does that help?

**Comment by OmarSherif96** [comment]
Hello Josefina,
Thanks that works for the Multiselect and Tables.

But I have two questions: 
1) Does this feature exist in the Dropdown ?
2) How can I use the Search component, like passing a data props to it so it can be able to search for it ? it's not clear in the docs.

**Comment by jnm2377** [comment]
@OmarSherif96 the Dropdown component doesn't support filtering or search. The ComboBox component is like dropdown but with filtering. https://react.carbondesignsystem.com/?path=/story/combobox--default It's like dropdown in that you can only select one option, but has filtering like the multiselect.
